cyruzzo/AboveVTT

abovevtt.css

I assume you meant it to be a rgba() black with opacity at 10%.

[css-fix] Refactored css box shadow

---

CombatTracker.js
Main.js
MonsterDice.js
abovevtt.css

- Top Menu styles and animations.
- Scene button to middle of the accordion to fix problems on smaller screens.
- Setting Top Menus on top of combat tracker.
- Combat tracker bottom buttons adjust to parent size.
- Send to players button.
WARNING
Minor changes to the js files, basically some classes added and some inline styles removed to avoid excess usage of important.

continuing beta styling

---

Main.js

`font-style:bold;` is invalid, to make a font bold we should use `font-weight:bold;`

[font-style-fix] Fixed css declaration

---

Fog.js
abovevtt.css

light styling

---

Token.js
abovevtt.css

hp aura and dead token X

---

Main.js
abovevtt.css

Removed unused css, amended text.

[minor_text_changes] Removed unused css, amended text.

---

Main.js

Tries to identify if the character sheet from DNDBeyond is loaded in half a second intervals for 10 seconds.
As soon as it's rendered syncs info with the VTT.

workaround for 10s wait for sheet to sync

---

CombatTracker.js
abovevtt.css

fix combat tracker bottom buttons when the container has a scroll

[bugfix] fix combat tracker bottom buttons when container has scroll

---

Fog.js

Allow drawings on top of tokens

Allow drawings on top of tokens

---

ScenesPanel.js

auto-replace gdrive links

---

Fog.js
PlayerPanel.js

[bugfix] bugfix different version data and select/measure layer problem

[bugfix] bugfix different version data and select/measure layer problem

---

Main.js
abovevtt.css

Changed button layout and styling somewhat, approved by SnailDice, Delete Data added to instructions

AboveVTT Cosmetic Changes

---

Main.js

[bugfix] Fix abilities values when modifiers are on the bottom

[bugfix] Fix abilities values when modifiers are on the bottom

---

Token.js

fix snap when multiple tokens are selected

fix snap when multiple tokens are selected

---

Token.js

Changing 'Reminders' to 'Markers' in context menu (Palad1N helped me)

changing 'Reminders' to 'Markers'

---

Main.js

increased draw color options

---

SceneData.js

SnailDice new scrapped maps

---

Main.js
abovevtt.css

fix side panel open for players

fix side panel open for players

---

.gitignore
Main.js

Alternate zoom fix, that keeps centering on mouse and trackpad functionality
Also adds a clamp util to constrain a value between a minimum and a maximum.

Fix zoom problem without losing trackpad zoom

---

MonsterPanel.js

* fixing broken footer removal
* yanking native dice panel (declutter)

monster panel cleanup

---

Main.js

fixed send to gamelog overflowing elements

fixed send to gamelog overflowing elements

---

Token.js

presets now use default colors

presets now use default colors

---

Fog.js
KeypressHandler.js
Main.js
Token.js
abovevtt.css

Revert "Select single token"

---

Token.js

Demo video https://imgur.com/a/niX4o3X

Add ability to lock multiple tokens at a time

---

KeypressHandler.js
Token.js

demo video https://imgur.com/a/4r03Xrm

move selected tokens using arrow keys

---

CombatTracker.js
KeypressHandler.js
Main.js
Token.js

demo video https://imgur.com/a/C4vmYJg

allow deleting tokens with backspace key

---

Main.js

Add AC and Speed listeners to character sheet to update tokens if the character's AC or speed changes.

Add AC and Speed listeners to character sheet

---

TokenMenu.js
abovevtt.css

Related to this comment: https://discord.com/channels/815028457851191326/815028804103307354/883647467869048862
I personally find this a better solution than growing for very large filenames, but I see how it could be annoying.

Token name truncation. (Added 20px spacing to bottom, truncate with ellipsis unless hovered)

---

Jitsi.js

Add tileview button for people who want a more regular videochat experience

Add tileview button to jitsi

---

CombatTracker.js
abovevtt.css

Added a round number to the combat tracker. The round number is window.ROUND_NUMBER and increases each time the combat loops. It is reset to 1 when combat is cleared or the "RESET" button is clicked. The round can be set manually.
DM View:
Player View:

Add Round Number Tracker

---

CombatTracker.js
abovevtt.css

Made the text in the combat tracker bigger, it's pretty unreadable in large resolutions.

Combat Tracker Text Bigger

---

Main.js

Attached the character sheet iframe event after the frame has been placed, as it was being called before the src was set and causing non-fatal errors. Also fixed some indentation.

Bugfix: Character Sheet iFrame load error

---

Journal.js
Main.js

Modify creature character send to gamelog to add classes for magnify. Also added the drop down for the magnify class in the notes, for future updates to use when parsing the note. To make that work you will need to parse the note adding "href" attribute to images matching the "src".

Other img popup

---

Main.js

Added a button to the top left of the character sheet to swap between 2 character sheet sizes.
Please see video for demonstration.
https://user-images.githubusercontent.com/82621530/143784044-d3bd9330-575a-4d8d-a387-0160c704cd48.mp4

Added resize button to character sheet window

---

Main.js

Server will post to chat log with the name of a player's character when they finish initializing.
please see video for reference:
https://user-images.githubusercontent.com/82621530/143979597-e4dcd3e4-0cf0-432f-855d-9a569549fdc5.mp4

Added msg to chatlog when player joins the table.

---

Token.js

Changed locked to only affect player control and added dmLocked to also lock tokens for DM.
see video:
https://user-images.githubusercontent.com/82621530/145080530-b2336c59-852f-46c6-b3d3-6955e4eddbd8.mp4

Rework locked and add dmLocked

---

Main.js
Token.js
abovevtt.css

Color Picker for the drawing tool, hopefully 100% bug free!
please see video:
https://user-images.githubusercontent.com/82621530/145339426-d20d2480-1b64-40b4-960d-209af68b33e7.mp4

Draw upgrades

---

Journal.js
SidebarPanel.js

This nests the journal tab content in a `SidebarPanel`

update journal tab to use SidebarPanel

---

Main.js
PlayerPanel.js
SidebarPanel.js

this nests the players panel content in a `SidebarPanel`

update players panel to use SidebarPanel

---

Main.js
MessageBroker.js
ScenesHandler.js
ScenesPanel.js

~~WIP, do not merge~~
Done, can be merged following code-review - see latest comment below.

Add support for non-youtube animated maps

---

AOETemplates.js
Fog.js
ScenesHandler.js
ScenesPanel.js
abovevtt.css

I am not a JS developer and don't know JS at all. However this seemed like a small enough change that I could figure out. 
Seemed like a simple change hopefully it doesn't break anything.

Add ability to change map units. (Defaulting to 'ft')

---

MonsterPanel.js
Token.js

Super simple additions for tiny tokens to the context menu and default monster token size tiny support. Thank you!

Tiny-Tokens

---

MonsterPanel.js
Token.js

This is ready to merge as far as i can tell

elev-tracker

---

Main.js

this should work fine too, i chose to do it in the main.js instead of the load.js page. hope thats not an issue?

warning for reset invite link created

---

EncounterHandler.js

see title for description. :D just kidding. removes the second scrollbar bug from the monster stat iframe windows. 1 liner!

removes second scrollbar for monster stat iframe

---

MonsterPanel.js
TokenMenu.js

Fix for tokens not respecting global hide setting

---

Fog.js

fix for players being able to select hidden tokens

---

Main.js
abovevtt.css

TODO: This requires testing of the message sending and dice streaming.
This changes the pc sheet to only use a single iframe instead of 1 iframe per pc. It also converts the animations from jquery to css.

refactor pc sheet structure

---

MonsterPanel.js

hide monster panel tabs that gives you access to the backing encounter

---

Token.js

Tokens sometimes have numbers and sometimes have strings for ids. This adds support for both

fix token.isMonster

---

Main.js

lock open the player sidebar immediately

---

MonsterPanel.js

add monster count to name, and update border color

---

Token.js

trim hp values of tokens

---

Main.js

Remove loading screen after 15 seconds if nothing else removed it..

---

Fog.js

#267 One of the requests for increasing text size when zooming out
Example video: https://youtu.be/9XqtT_IPLl4

Calculate ruler text size based on Zoom

---

Main.js

bring in player css to properly style sned to gamelog items

---

Token.js

fixes #298 
added trim to text box input as I saw it mentioned that placing whitespace can have adverse effects
made dead X a hidden element, shows when dead
did some cleanup of related code as kept seeing duplicated fragments

#298 : made dead X a hidden element, shows when dead

---

CombatTracker.js

Fix the combat tracker being behind the map.

Fix so combat tracker isn't behind map

---

abovevtt.css

Fix mega wizard being behind map

Add z-index for mega wizard

---

Main.js
abovevtt.css

Fix player buttons behind bar

---

Main.js
ScenesPanel.js

fixes #337
https://user-images.githubusercontent.com/9283242/160083152-333cbdf3-57bb-412f-a62a-1dbe58d9a451.mp4

#337 : scene position is now stored on page refresh

---

Main.js

Fixes #324 DM view was ok from when Bain did the dice fix.  This fixes the player view

Fix player view game log height

---

EncounterHandler.js
Main.js
MonsterPanel.js
Settings.js

remove unused experimental features

---

Main.js
MessageBroker.js

fix slow dice

---

SidebarPanel.js

Minor QOL improvement, clicking add clears the url so you don't have to manually remove the url

adding a token to the journal clears the input

---

Fog.js

Fixes #379 
Mouse events were being added without being removed

FIX:  Remove mouse events from #black_layer

---

Main.js
abovevtt.css

Fixes #371 and Fixes #370
DNDBeyond's new character sheet setup changed this.
https://user-images.githubusercontent.com/65363489/161300043-efeb0c06-1602-43cd-a8fd-de7e75faf972.mp4

Fixes dice hiding and rolling under log

---

Main.js
abovevtt.css

Closes #376 
Introduce and apply a css variable for font-size for tokens based on zoom level. I can adjust the scaling if anyone thinks it's too much/little.
https://user-images.githubusercontent.com/65363489/161350617-bcf63235-184c-425f-b10a-34306c68e3e2.mp4

Add variable and set font scaling for token names

---

MonsterDice.js

uplifted to fix issues with scrolling and context menu not being applied in the correct place
and issue with some dice notations not being picked upas rollable
Tested using giant rat and steel defender who both have slightly different dice notation in their blocks. Damn you DNDB!
F-ER does not have damage dice in brackets, nor the "average damage"
https://user-images.githubusercontent.com/9283242/161730275-9080fc5f-d005-4fec-8306-f62264260bfe.mp4

extra dice rolling now works again

---

Fog.js
Token.js

fixes #251
Thanks to @Azmoria cursor events were exactly what I was after I just didn't know it
[video here](https://discord.com/channels/815028457851191326/832199739398946817/956469999357276200)

251 tokens without player interactions

---

Token.js

fixes #343
This one was annoying and took far longer than it should have for some a simple block of code.
https://user-images.githubusercontent.com/9283242/160187564-61cb2d16-5bdf-4367-b09e-03e2a9007454.mp4

#343 : tokens with auras now hide their auras from players

---

Main.js

Mac users are better than windows users ;)

offset gamelog by scrollbar size

---

Token.js

fix: token images don't change while hidden

---

Fog.js

Fixes player being able to drag select in fog

---

Token.js

This fixes #419 
This changes the check if player id function to return false on an undefined id.
This fixes the super mega wizard due to at some point it running that function when creating a new token and running build_hp. Tokens might be the handles you drag around. I'm not sure but this fixes it.

Fix: Get Super Mega Wizard to appear again when clicking the button.

---

abovevtt.css

Fixes #442 
This stops the sidebar css from applying to the sidebar on that page.

Fix combat log positioning on DDB campaign view

---

abovevtt.css

Fix context menu behind custom tokens

---

SidebarPanel.js
TokenMenu.js

this also fixes the monster configure button within encounter folders

fix: change image doesn't work for monsters

---

Token.js
TokenMenu.js
abovevtt.css

The hide button wasn't changing state with the tokens. Now it does.

fix hide token button styling in context menu

---

SidebarPanel.js
TokensPanel.js

Just some accessibility tweaks for easier understanding of what buttons do

Add titles to buttons in the sidebar

---

DiceContextMenu/DiceContextMenu.js
MonsterDice.js

fix for dice rolls not working when modifier is missing

---

Fog.js
ScenesPanel.js

Fixes #488
There was an infinite loop when waiting for `i>value` but `i` was negative and was having more subtracted from it. I changed it to abs values.

Fix: Stop Super Mega Wizard from crashing the site

---

TokensPanel.js

fix walking speed displaying passive perception

---

MessageBroker.js

This is the client side part of the solution for https://github.com/cyruzzo/AboveVTT/issues/421
The cloud side solution can be found here https://github.com/cyruzzo/AboveVTT-Backend/pull/3

include playerSceneId in cloud messages

---

TokensPanel.js

fix monsters with CR 1/2 showing as CR 0

---

ChatObserver.js

This fixes whispers which currently send no text.
Fixes #526

Fix whispers

---

Fog.js
MessageBroker.js
Token.js

fix draw_mouseup select calling place() too much
fix delesect_tokens calling place() too much
debounce drawing box and check_token_visbility

Fix performance issues when there are many tokens

---

Token.js

This definitely feels better for a dragging single token as a player. I'm pretty sure it also feels better for when more than 1 is selected but I could just be crazy - it's pretty minor on my end. 
I'm not sure this really fixes the root of the problem but it reduces the loops (especially for a single token) so it feels more responsive. It's probably not the root cause since it isn't happening on the DM view. It might be one of those things like the scroll throttle in player view that dndbeyond put in.

Fix: Better feel for dragging as a player

---

KeypressHandler.js
SidebarPanel.js
TokenMenu.js
TokensPanel.js
abovevtt.css

* Fixes a bug where changing the image of a token just doesn't work.
* Fixes some weird layout issues in the footer of custom image modals.
* Updates the custom image title to reflect the current state ("Replace Default Image" vs "Add More Custom Images")

fix some custom image modal bugs

---

Fog.js

fix for clear not clearing player side - https://discord.com/channels/815028457851191326/859099351711875092/982845236776677428
fix for brush not drawing correctly - https://discord.com/channels/815028457851191326/859099351711875092/983039447773896745
fix for previous circle drawing on click after clear - https://discord.com/channels/815028457851191326/859099351711875092/983039447773896745

0.77RC2 fixes

---

ScenesPanel.js
abovevtt.css

https://discord.com/channels/815028457851191326/859099351711875092/983199857529458759

fix scene image validator

---

TokensPanel.js

fix passive perception / walking speed not working

---

Main.js

Fixes #252 by removing the mobile fallback div and adjusting mobile and tablet styles to remove the remaining leftover whitespace
Left the remaining empty `.header-wrapper` in place for now.

Hide header on mobile sheet iframe

---

abovevtt.css

https://user-images.githubusercontent.com/65363489/173204855-bcfdd2de-3d3d-4d9f-bd8b-4ef22a6029ac.mp4

Blur join link on campaign page

---

Token.js

Fixes #591 
https://user-images.githubusercontent.com/65363489/177887603-baa9c59f-62bb-4497-83fb-48e6c2120a39.mp4

Fix aoe tokens rotating

---

TokenCustomization.js

This fixes #595  .
People that have used the release candidate and had this issue needs to manually rollback_token_customizations_migration() from console and reload

Fix migration to tokencustomizations

---

Token.js

closes #596 
thanks to @Azmoria

AoE tokens are once again selectable

---

TokenCustomization.js

fix duplicated ddb portraits

---

ScenesPanel.js
abovevtt.css

- DM map row only appears if enabled
- Update placeholder text of map lines
- Window is moveable
- Sized to fit content as menus appear
- When clicked into the URL lines and Name will select all text automatically for QoL.
- Slight appearance adjustments
Addresses Part 2 of #147 
Example:
https://www.youtube.com/watch?v=6p40ompCV-Q

Scenes panel adjustments

---

Token.js
abovevtt.css

This fixes #347 for both players and DM's. This should return consistent results and show the appropriate health and temp health levels on all tokens now.

Fix inconsistent temp hp aura

---

TokensPanel.js

A missed part of the fix for #627
This should fix tiny token overrides.

Fix tiny token override in #627

---

Main.js
abovevtt.css

This functions pretty well for monsters I figure I may as well put it up for a PR. We can expand what pops out as we go.
Add a popout function and apply it to monster statblocks. This popout function will work for other things in the future we wish to popout as well. 
The start / first part of #630

Popout monster stat blocks

---

CombatTracker.js
Token.js
abovevtt.css

https://www.youtube.com/watch?v=HpT_kFUdsGw
Enable changing monster hp directly from the combat tracker.
credit to @Azmoria for help with CSS and bugfixes

Enable changing monster hp from combat tracker

---

Main.js
Settings.js

This change will close cyruzzo/AboveVTT#606.
I'm not sure where/how settings are saved, because the selected value is **not** persisted between page reloads.

Close cyruzzo/AboveVTT#606 by setting default value to false

---

TokenMenu.js

This was trying to access DM only variables.

Fix player view token adjustments

---

TokenMenu.js
TokensPanel.js

Fix token customization in the menu. 
It's trying to find a token to clamp when we don't have a token yet. This just sets defaults for when we are using the panel instead of the token context menu.

Fix configure options not showing up

---

Token.js

Arggh - I had this line commented out when testing and missed putting it back so the error didn't throw and it worked. Another line with DM variable that should have been changed.

Fix player view context menu size changing - part 2

---

README.md

Update README.md Contributing section to fix typo.

fix: fix typo in README.md "Cnsiderations:" -> "Considerations"

---

Fog.js
MessageBroker.js
Token.js

I'm pretty sure this fixes at least a portion of the player view drag while measuring performance issue.
See example video - left is current, right is this PR:
https://www.youtube.com/watch?v=LX9zVdeZr0c

Improve ruler performance while moving a token in player view. Improve token selection/movement performance in firefox.

---

Token.js

Reported by ZorkFox on discord
Problem:
Fix:

Fix custom condition colors in Firefox

---

Token.js

Errors out on `tok` calls should be `$(tok)`

Fix missed jquery selectors in performance fix merge

---

Main.js
MessageBroker.js
abovevtt.css

This adds a `center player map on ping` toggle for DM's. I've seen this request a few times most recently by garrett on discord https://discord.com/channels/815028457851191326/815028716040224818/1015333028672843848
https://www.youtube.com/watch?v=o0A8XVVWkMc

A toggle button for DM pings centering player view

---

CombatTracker.js
abovevtt.css

https://user-images.githubusercontent.com/65363489/189316603-21e15dd0-4205-433c-aea6-553adac53688.mp4

Fix position of combat tracker name hover when scrolled

---

CombatTracker.js

After no longer having my local storage or new campaigns it errors out doesn't get to the reorder function.

Fix - beta combat reorder on load (error when local data undefined/null)

---

Settings.js

I believe this fixes NiKki's import problem reported on discord 
https://discord.com/channels/815028457851191326/852495991227809802/1032984245909598348

Fix -  import token customizations

---

Settings.js
Token.js
TokenMenu.js

Closes #256 - condense the options into 1 dropdown

QoL - Condense lock and player restrict

---

Jitsi.js

This could have some "race condition" issues.. but I didn't comeout with other quick solutions at the moment...

Jitsi workaround

---

Settings.js
Token.js
TokenMenu.js
abovevtt.css

Closes #703
Decided to build it since it wasn't too much more work from what I already had from mock up. See #703 for more details.
Example https://youtu.be/aRqNBFnE5oM

QoL - condense and adjust health visuals (bar/aura) options

---

abovevtt.css

Reported in discord https://discord.com/channels/815028457851191326/815028804103307354/1037351897469816943
Example of fix:
https://user-images.githubusercontent.com/65363489/199564001-a872c41a-c5dd-482e-88ef-49f479dd2d18.mp4

Fix - ordered, unordered lists not displaying their marker in notes

---

Main.js

Fix - Players with quotes in their name should now be able to ping

---

Token.js

This fixes auras not being aligned after scaling changes for map performance

Beta Fix - Auras should now align properly on scaled maps

---

Fog.js
abovevtt.css

To go along with the new scaling stuff. This stores the scale the fog was placed at so that it can be interpreted when on a different scale. Old/already placed fog won't have the scale data so it won't adjust.
Fog Example video:
https://youtu.be/XdfdIqEbS1Y
Drawings Example Video:
https://youtu.be/g7X6z_1e2CU
Edit:
Added a quick fix for https://discord.com/channels/815028457851191326/815028804103307354/1071865214305321050

QoL - Scale fog and drawings with map. (New fog/drawings only)

---

CombatTracker.js

Closes #742
Example:
https://user-images.githubusercontent.com/65363489/216809375-d4123b86-18b7-4f77-85d4-1a7b5d81e350.mp4

Add Prev button to combat tracker

---

CombatTracker.js
MessageBroker.js
abovevtt.css

I combination with @cyelis1224's work (https://discord.com/channels/815028457851191326/930926587392692335/1056453785603559434) I think this will close #741
Example
https://user-images.githubusercontent.com/65363489/216824783-429a4e01-ecc4-4e21-a020-02cd30f5af1e.mp4
Edit: To do

Allow players to end their own turn.

---

ScenesPanel.js

Adds a search bar for the title.
https://gyazo.com/85a8b4cdfb33e681f98f55e25495bc27
Completes #760

feat: add a search for the scene maps

---

ScenesPanel.js
abovevtt.css

Adds a basic cancel wizard button - until we decide what other improvements we want to make I've just placed it at the top of the screen for ease of access. 
https://youtu.be/-hahDotEUFE

 QoL - Add cancel wizard button to mega wizard & Wizard dialogs are dragable

---

Settings.js

Open to other naming suggestions as well

Since hp bars aren't always 'bar' relabel it to HP Meter

---

ScenesPanel.js
abovevtt.css

For when maps you just can't quite get to line up these bars should allow for more precise adjustment when needed. We can pretty them up as we adjust the UI.
https://www.youtube.com/watch?v=WOtus3jyNdk

QoL - Add minor adjustment bars to grid wizard

---

ScenesPanel.js
abovevtt.css

People have requested a number input for the darkness filter beside the bar. 
I also made a few other adjustments on the panel, added a label to the grid line width. Some appearance adjustments. Few other ideas for this but this is a first pass and I think the number inputs are a useful to have item.
Edit:
Also added link is video label as people often confuse this with enabling or disabling the map in support or enable it not knowing what it does/by accident.

QoL - Scene panel appearance adjustment, add label and number inputs.

---

abovevtt.css

Recent push broke the css file. Not sure how I did that was working on my end. Ooops

fix - broken css file missing }

---

DiceRoller.js
Main.js

There are 2 main parts to this
1. Custom dice roll buttons were not being injected when the DM opened character sheets.
2. Updating the notes field didn't always update the button
To get this working on the DM side of things, I had to update `getCharacterStatModifiers` to dig through and parse `window.PLAYER_STATS` as well as dig into the currently open iframe to find the proficiency bonus.  
I also had to update `replaceModifiersInSlashCommand` to allow parsing on pages other than the character page  
Finally, I had to pass the iFrame to `observe_character_sheet_dice_rolls` when the character sheet opened
To inject the buttons when the notes field was updated, I had to update the MutationObserver to actually iterate through the mutations looking for updates to the elements we care about. …

beta fix: inconsistent dice roll button injection

---

Main.js

Example
https://user-images.githubusercontent.com/65363489/217938067-22768bf4-1286-479c-8d34-71013dbb3f7c.mp4

QoL - Center Ping in viewable map area (takes into account the sidebar)

---

Fog.js

Nate found it was still having issues and I think this catches them all now.

Fix - another fog check spot missed for css -> ctx

---

Main.js

Revert "0.84-beta2"

---

Fog.js

When fog is removed light auras aren't shown properly. This should fix that

Fix - properly show light auras on fog reveal.

---

MessageBroker.js

I split out the fix for the text loading because I think the fix should go in before release but the hidden can wait.

Beta Fix - text on scene should load correctly

---

Journal.js
abovevtt.css

I think this is a good first pass at adding some ddb styling and containers to the journal editor. Part of #854 
https://user-images.githubusercontent.com/65363489/219900215-48236c20-e929-4ca7-9e1c-ed25f2c6de15.mp4

Journal Styling Update - Add DDB containers and styling to editor, Add view button to editor titlebar.

---

Fog.js
MessageBroker.js
Text.js

Add a quick option to hide text from players when right clicked.  Closes #853 - came back to this quicker then I thought but was looking at the loading issue anyway.
https://user-images.githubusercontent.com/65363489/219957343-9b487466-5c3a-41e4-b4b9-93db452fc98e.mp4

Add hide text from players button to text controller and hide on right click.

---

Fog.js
MessageBroker.js

Adds a bucket fill hide/reveal options to fog.
https://user-images.githubusercontent.com/65363489/220970688-6030f938-7231-4c33-b1fc-a27defcb6ae2.mp4

Add bucket fill fog options between walls.

---

Fog.js
Token.js

https://user-images.githubusercontent.com/65363489/221044794-fa897090-9a48-4465-8b3d-21817cac50d3.mp4
Fixed an if statement for non-player reveal vision. 
Applied collision detection to arrow keys

Beta Fix - Arrow keys should now also detect wall collision.  Fix revealed non-player vision when no token selected

---

Main.js

Beta - Swap button order for walls/fog etc

---

Settings.js
Token.js
abovevtt.css

Map Pin token style

---

Settings.js

People with low powered computers have performance issues with these features

change cursor and ruler settings to be off by default

---

MessageBroker.js

Thought I caught all these but missed this one.

Fix - remove light containers on scene load/swap

---

CombatTracker.js
Fog.js
Main.js
MessageBroker.js
SidebarPanel.js
Token.js
TokensPanel.js
jquery.contextMenu.js

This feels like it shouldn't be this easy, and I'm worried that this will break something else considering this function hasn't changed in months. Everything I've tested seems to work, though.
I also fixed a bunch of bad `for` loops. I often see `i is not defined` because some of these execute before a different variable had the chance to set it globally. None of these should be global variables.

Fix - Snap to grid miscalculation

---

MessageBroker.js

not sure if this is the best way to do this, but it seems to work

clear drawings on scene change

---

CharactersPage.js
Fog.js
Main.js
Token.js

Improving fog by removing unused selects, passing around the context and canvas some to reduce grabbing it, and move some logic/selects to only run when needed. Use `putImageData` instead, it is much more performant.

Improve Fog DOM read/write performance

---

TokenMenu.js
abovevtt.css

I added conditions to the quick roll menu. I also made some UI updates based on some feedback I saw.
There was an issue with the dropdowns when the menu is a popout. I didn't have time to look into very much but the dropdowns don't seem to work on the cloned window. It didn't feel terribly important, but if someone who knows JS better than me can take a crack at it.

Add conditions to quick roll, and UI changes

---

Fog.js

Quick fix for one other spot we missed

Beta Fix - Tokens properly hide out of line of sight

---

manifest.json

0.91 Version bump

---

Text.js

https://github.com/cyruzzo/AboveVTT/issues/914

Close text controller on tool swap, esc, clear all

---

KeypressHandler.js

I believe natemoonlife and mikedave mentioned this in discord. Low hanging fruit that is a nice qol improvement.

Feat - Add `space` keybind for pausing players in DM view.

---

CombatTracker.js
MessageBroker.js

Remove unused css and have combat tracker order be correct with dm not connected

#1096 Fix combat tracker player sync

---

manifest.json

Fix font block by chrome
https://github.com/cyruzzo/AboveVTT/issues/1105

Update manifest.json to fix font blocking 

---

Token.js

https://github.com/cyruzzo/AboveVTT/issues/1104
I don't think we need to run `update_and_sync` on movement from what I can tell. The issue is we are appending the temp hp when we get the hp to set for the currentHp in the hp object. This was the best way from what I can tell vs hacking it/adding another hp getter/setter in place of the one we use on `baseHp`. If I missed something, and we do want `update_and_sync` to run let me know and ill go the longer approach by modifying how its getting/setting hp.
Also, went ahead and modified the `var` to `let` for GC improvements and found one small for loop that was using the same objects twice in scope. These pieces aren't part of this bug, so if you want I can break it out. Just figured should tackle it while I am in there.

Fix temp hp bug

---

Fog.js

I missed } in my last change to my PR 🤦.
I should have tried to load in before pushing the beta, fixing this then putting out beta.

Beta Fix - Loading error

---

Fog.js
ScenesPanel.js
abovevtt.css

Beta Fix - Grid wizard being blacked out and 'shadow' auras on 0 darkness maps

---

Token.js

Instead of removing it during the for loop remove them all at once at the end after a timeout

Delay removing click_pause on drag stop

---

Token.js

Missed this line when I did the default changes

Beta Fix - Missed default Light change

---

KeypressHandler.js
Token.js

Fix notes not cleaning up correctly, eventually eating all localstorage

Support Copy Paste at Cursor and Copying of Notes with clean up of deleted token notes

---

Main.js
MessageBroker.js
audio/mixer.js
audio/ui.js

The animated map slider isn't working for regular html videos only the youtube player. This should resolve that.

Fix - volume sliders for html video (gdrive and other non youtube) volume

---

Fog.js
Main.js

Add's an option for drawing light. This type of light may be easier for some forms of static light as well as perform better then individual token light.

Feat - Light drawings

---

Main.js

This fixes the light layer blend mode

Internal - fix light layer blend mode before beta

---

Fog.js

Bucket fill for drawings and light were being stroked black. This should resolve that.

Beta Fix - Stop Bucket Fill light from being stroked black

---

Fog.js

Adds a three point rect tool - this was requested on discord.
It cuts drawing rectangles for rooms or buildings down by 2 clicks each compared to the polygon. Although not substantial when doing one or two it can be quite a bit when it gets to dozens or more.
Closes #1198

Feat - 3 Point Rect tools to assist with angled rectangles

---

Fog.js

Convert 3point rects for walls to wall lines so the eraser and convert to door work.

Beta Fix - 3 point rect walls should be erasable and convertible to doors

---

Settings.js
abovevtt.css

This adds an export current scene only button - to help with community premade maps

Add export current scene only button

---

SceneData.js

Updates the icespire peak maps configured by firetech

Update to some icespire peaks maps configured by firetech

---

MessageBroker.js
audio/mixer.js
audio/ui.js

Check if the video map exists before trying to adjust the volume. These errors didn't really affect anything but better to not have them in the log.

Beta Fix - Prevent a few errors when changing video volume

---

EncounterHandler.js
Main.js
MonsterDice.js
MonsterStatBlock.js
SidebarPanel.js
TokenCustomization.js
TokensPanel.js
abovevtt.css

This adds open5e monsters to the sidebar. 
Customizations, adding the tokens etc should all work.
To Do:

Add Open 5e Monsters

---

manifest.json

Bump to 0.96

---

CombatTracker.js
MonsterStatBlock.js
StatHandler.js
TokensPanel.js

Add damage adjustments, condition immunities
Fix rolling initiative for open 5e monsters

Beta Fix - Auto roll initiative open5e monsters and add their condition, and damage immunities, vulnerabilities and resistances,.

---

TokensPanel.js

Format the open5e monster spells so they are readable and have our spellslot trackers

Beta fix - Format open5e spells

---

CharactersPage.js
abovevtt.css

Fixes heal rolls in player view when ddb dice are disabled. Style the player rolls so the DM knows what players are rolling.

Beta Fix - When DDB dice are disabled heal roll buttons should work in player view, player view gamelog roll styling

---

CharactersPage.js
CoreFunctions.js
DiceRoller.js
LoadCharacterPage.js
Main.js

This adds chat rolls to our own roller when ddb dice are disabled. 
Enables the `rpgRoller` experimental setting in the DM view pc iframes and sends the message through tab communication.

Beta - Player frames in DM view and chat rolls should work now.

---

CharactersPage.js
DiceContextMenu/DiceContextMenu.js

Still have to figure out the `send to` for rolls in the context menu but this should give a basic advantage/disadvantage and crit/flat rolls

Beta - When using non-ddb dice right click menu should now function and custom buttons should be styled in the game log.

---

MonsterDice.js

Add styling for non-ddb dice for monster rolls

Beta - When using non-ddb dice monster rolls gamelog styling

---

CharactersPage.js
DiceRoller.js
MessageBroker.js

Make sure modifiers are added when rolling with context menu. Add initative to pc when rolled.

Beta - For non-ddb dice fix modifier on adv/dis, auto add PC initiaive rolls to combat tracker

---

Token.js

Small fix to ensure the ghost is always removed when peer streaming is on. 
QoL to increase the border size for visibility.

Fix - make sure token drag ghost when streaming measuring is removed; QoL - increase border size for visibility

---

MonsterDice.js
TokensPanel.js

Missed stripping a space and the roll type for damage rolls.

Fix - Open5e monster adv/dis and crit dmg on context menu (ddb dice)

---

Main.js
PeerCommunication.js
Settings.js
Startup.js
abovevtt.css

Also fixes the button positioning for DM so when a button is removed other buttons after slide over. This only applies to projector and cursor atm.

QoL - Add a quick toggle when projector mode is enabled

---

Journal.js

Add another type of allowed chapter and make it a little easier to read from my last change.

Fix - An error when openning a imported DDB journal chapter that is an attachment like a map.

---

MessageBroker.js
ScenesHandler.js

This should help with the amount of messages we get where we suggest shrinking images.

QoL - Size down large maps automatically to help performance. 

---

MessageBroker.js
ScenesHandler.js
ScenesPanel.js

Fixes the beta so it only applies to new custom scenes as there was issues with old scenes.

Beta Fix - Scene auto scale only on new custom scenes

---

Fog.js
ScenesHandler.js

Fix alignment and the grid wizard on auto scaled maps.

Beta Fix - Grid alignment on auto scaled maps

---

MessageBroker.js
ScenesHandler.js
ScenesPanel.js

This should fix it so that when the scale is changed the grid lines up with the new scale.

Fix - Grid should line up/scale with scale changes

---

MessageBroker.js
ScenesHandler.js
ScenesPanel.js

When cancelling the wizard hpps, vpps, offsetx and offsety we're incorrect.
Apply the auto scaling to all maps, and convert old maps.

Beta - apply auto scaling to all maps.

---

Fog.js
MessageBroker.js

Add the conversion scaling for all maps.

Beta - scaling conversion for drawings, light, fog etc. on old maps - no user input required

---

Main.js
abovevtt.css

Added a compatible tools section in help.
Currently only added dddice and dungeon alchemist. Will add more as they come up.

Compatible Tools section in help

---

MessageBroker.js

scale_factor sometimes is not set so set to 1 in these cases.

Beta Fix - Issue with tokens being placed due to scene data being set incorrectly

---

ScenesHandler.js
ScenesPanel.js

There's a few more places the data needed to change as well

Beta - fix issue with old scene conversion

---

Fog.js

Set the temp overlay to soft-light blending mode when on the light menu.

Beta - Light drawings set preview to soft light

---

CoreFunctions.js

The container wasn't minimizing so the containment was acting as if the whole window was open. Also it wasn't saving the location properly.

Beta Fix - Issue with moving, saving the location of minimized ddb journals.

---

ScenesPanel.js

This resolves an issue when we check for upscaling and the 5ft, 10ft etc options.

Beta Fix - issue with upscaling and different ft options in grid wizard

---

CoreFunctions.js
Journal.js

A requested QoL feature to quickly pop out the site.

QoL - popout button added to ddb chapters journals

---

Journal.js

This adds rollable buttons to journals automatically when a rollable notation is detected.

QoL - Add rollable buttons to journals, will scan for matching phrases (1d20,  1d6+4, d6, etc.)

---

ScenesPanel.js

Fix the grid preview size on scaled maps in beta and remove redundant function

Beta Fix - Grid preview size on scaled maps

---

ScenesPanel.js

Forgot auto scaled maps, and offset

Beta Fix - Preview fix for auto scaled maps as well

---

ScenesHandler.js
ScenesPanel.js

I missed updating the scene_handlers window var data when persisting - this caused a couple glitches. Also look to see if a new or old map for grid preview.

Beta Fix - When scene is saved update session data and fix grid preview for new/ old maps

---

Journal.js
Token.js

Adds the rollable buttons to token notes hover as well.

Beta - Add rollable buttons to token note hover

---

Journal.js

Adds some of dndbeyond's searchs as importable chapters for those that want access in app.
https://cdn.discordapp.com/attachments/1127009242327547924/1133465552191488010/2023-07-25_14-26-06.mp4

Add compendium searchs to importable journals

---

Token.js

Fixed single token drag, this should also fix group drag.

Beta Fix - issue with group drag also skipping lines due to double rounding

---

ScenesPanel.js

Adds a quick explanation of what to expect for player view to the light settings panel.

Beta - Add explanation text to light settings panel

---

CombatTracker.js
Journal.js
Main.js
MonsterStatBlock.js
TokenMenu.js
TokensPanel.js
abovevtt.css

Adds custom monster stat blocks as an option when customizing a token. This works for journals as well.
Example:
https://www.youtube.com/watch?v=PH3ZSDowPAc

Feat - Custom Monster stat blocks using journals

---

Journal.js

Fixes `&nbsp;` issues with regex when looking for journal dice formulas.

Beta - dice pattern recognition adjustment for journals

---

Main.js
MessageBroker.js
ScenesHandler.js

This was reported on discord a bit ago - wasn't a priority at the time due to uvtt files coming with grid data. This should resolve the issue though incase people want to adjust the grid.

Fix - issue with grid wizard on uvtt maps

---

Fog.js

I think I changed this a bit back for the wrong reasons. With new scaling this wasn't picking up the correct sizing. Go back to using actual reveal all.

Fix - issue with reveal all fog on some maps

---

Journal.js
MonsterStatBlock.js

Example:
https://youtu.be/JhpumD_2yJA

Add ddb tooltips to journal/custom stat block link type options

---

Main.js
abovevtt.css

Adds a video playlist section in help. I want to move some videos over to youtube and update them to add to this list.

Add Video playlist tutorial section in help

---

Main.js
abovevtt.css

Adds some more common help sections for different parts of the UI. Write ups aren't complete but we only require an update to add more tabs/bookmarks.

Add help sections with bookmarks - thanks Fuzzy Bunny for the writeups

---

MonsterStatBlock.js
TokenMenu.js

Runs the add ability tracker function on custom sheets.

Add spell trackers to stat blocks copied from ddb

---

Journal.js
MonsterStatBlock.js
Token.js

Add auto tooltips and formatting for custom monster sheets. Add [spell][/spell] shortcut for official spells.

---

Journal.js

a couple fixes for the custom stat block that was causing it to display the html due to replacing a data attr. Fix the trimmed spacing.

Beta Fix - Custom stat blocks double tooltip links causing jank, and fix odd spacing

---

Journal.js

Fixes tooltip issues when both manual and auto detect are used.
Also caches id's we store and a faster way to get them from dndbeyond - so we aren't making as many requests to them.

Beta - Fix some tooltip issues and a better way to fetch ids.

---

Journal.js
MonsterDice.js
MonsterStatBlock.js

attempts to automatically add spell trackers to custom blocks

Add spell trackers to custom statblocks

---

TokensPanel.js

This was unintended to be on pc tokens to begin with and is causing errors.

Fix - remove custom stat block from pcs as it was causing errors

---

Journal.js
abovevtt.css

Layout fix - made a mistake in adding <p> on split without capturing it as well.

Beta - layout fix for custom stat blocks

---

Journal.js

Adds roll types and action type to custom monster attacks.

Add roll type and title to attacks in custom monster sheets.

---

abovevtt.css
audio/track.js
audio/ui.js

example
https://github.com/cyruzzo/AboveVTT/assets/65363489/1438d4a2-40f6-4ebd-ad81-a60b5541720b

Add audio search tags to right click menu, fix track tags being removed on edit track name/src.

---

MonsterStatBlock.js
TokensPanel.js

Should work with official, open5e and custom stat blocks.
https://github.com/cyruzzo/AboveVTT/assets/65363489/c6108d63-81a2-4443-8c29-18479e21aa20

QoL - right click monster feature name to send feature to game log.

---

Journal.js

Couple more shortcuts and ddbs renaming

Add DDB Monster and Magic Item shortcuts. Add shortcut naming eg. [monster]Wolf;Wolves[/monster] displays as Wolves

---

Main.js

Correct tab name to reflect section in help.

Beta - Correct tab name

---

CampaignPage.js

Commented this out so I could join as DM to help someone troubleshoot in their game.

Beta Fix -  Accidental commit of test/troubleshooting code.

---

audio/mixer.js

Fixes a few issues with the last fix regarding audio tracks, position and volume.

Beta Fix - issue with last fix to prevent track from playing when another is paused

---

Fog.js
Token.js

Adds windows to the walls options.

Feat - add windows to wall options.

---

Journal.js

Errors out on non-match in ddb ids. Changed it to hardcode this particular id.

Beta Fix - issue with opportunity attacks tooltip preventing custom statblocks from opening

---

Journal.js
abovevtt.css

Adds the red separator used in monster stat block as a journal format.

Add monster ability separator in journal format menu

---

Journal.js

Fixes some copy and paste issues for the custom statblock replacing class names or links.

Fix - custom statblock tooltips replacing html elements/class names

---

Journal.js

Fixes custom statblocks to be cross campaign.

Fix - cross campaign custom statblocks

---

Journal.js

should be != not == statblock for regular notes.

Fix - journal note persist should be != statblock

---

manifest.json

Chore - 1.0 bump

---

Main.js

Change to working discord link

Fix - expired discord link in help

---

Token.js

Tokens weren't loading in at full size sometimes this should resolve that.

Fix - issue with tokens not loading in at the correct size.

---

SceneData.js

Wave echo cave import data was off due to the auto scale - adjust scale back to 1.

Fix - issue with wave echo cave import data

---

Fog.js
ScenesHandler.js
ScenesPanel.js
Token.js
abovevtt.css

Example :
https://youtu.be/VL_0TdEps0o

QoL - Grid wizard update; Feat - basic hex grids

---

Fog.js

small fix to grid wizard update

Beta Fix - Ruler and token size to be more accurate on horizontal hex grid

---

Fog.js

The move polygon was missing the duplicate end point.

Fix - issue with player token movement to the right and up.

---

Fog.js
Token.js

Enables snap movement with drag and arrow keys on hex gridded maps

Beta - enable snap to grid and arrow movement for hex gridded maps

---

Fog.js

Fixes an issue with hex grid measurement.

Beta Fix - issue with ruler measurement for hex grid

---

Fog.js
Token.js

Beta Fix - Hex snapping on scaled maps.

---

Token.js

fixes and issue with move key when snap disabled.

Beta Fix - issue with move keys when snap disabled on hex grid

---

MessageBroker.js
Text.js

A couple text fixes from reports in discord
https://discord.com/channels/815028457851191326/815028804103307354/1147050512332623945

Fix - issue with text controller on edit text; issue with text check closing all text windows.

---

Fog.js
ScenesHandler.js
ScenesPanel.js
Token.js
TokenMenu.js
abovevtt.css

Fixes a few issues with snapping and adds in sliders for hex scenes in the wizard.

Beta - Add minor adjustment/skew sliders for hex scenes; Fix some more snapping issues.

---

Fog.js
Token.js

Due to undefined new variables old scenes wern't working

Beta Fix - loading scenes made prior to beta should work again

---

built-in-tokens.js

Replaced flame 1 link with reupload to our discord

Fix - flame 1 gif link was broken due to site going down.

---

ScenesPanel.js
Token.js
abovevtt.css

Some more fixes for older maps that don't have new variables. 
Also some fixes for splitting the grid and upsq/fpsq getting picked up properly. Adjusted the instructions on some grid types/setting selections.

Beta - More fixes for old maps and wizard improvements/fixes.

---

ScenesPanel.js

The offset needs to be set and parseFloat needs to be done.

Beta Fix - accidental removal of parse float that was needed when manually adjusting grid

---

Fog.js
ScenesPanel.js

This disables other tools and sets the wizarding variable again.

Beta Fix - disable tools other than select in wizard again

---

Journal.js
Token.js

Missed applying these to regular journal and token note hover.

Fix - apply tooltip links and shortcuts to regular journal and token notes.

---

Settings.js
abovevtt.css

More export options and better naming of exports

---

SidebarPanel.js
TokenCustomization.js
TokensPanel.js

This give tokens in the abovevtt and ddb folders customization options.

Allow token customizations (including stat blocks) to be applied to built in tokens.

---

Journal.js
abovevtt.css

This allows journal folders to be put in other folders.
Example:

QoL - Journal folders draggable into other folders.

---

Journal.js
abovevtt.css

Fixes some issues with scenes panel reordering due to journal droppable. Add greedy and refreshpositions to dropable/sortable to eliminate some difficulty sorting folders.

Beta Fix - Fix scenes panel error due to journal sorting; fix issue with journal droppable positions

---

Journal.js

Fixes journal subfolder sorting order.

Beta Fix - journal subfolder sorting

---

Journal.js
Settings.js
TokensPanel.js

Fixes statblocks exporting and importing. Adds it to token customization exports.

Fix - Custom statblock import/export

---

Settings.js

Pasted this in wrong spot and didn't reverse it.

Beta Fix - accidental copy paste causing issue with journal export

---

Fog.js
ScenesHandler.js
ScenesPanel.js
Token.js

Fixes arrow key movement in a few places. This was due to both an existing issue and my changing to the new movement canvas for movement checks.

Fix - Arrow key movement when token vision is disabled; Beta Fix - Arrow key movement when grid wizard hasn't been run/maps made pre beta.

---

Fog.js
KeypressHandler.js
Main.js

Add's a ruler menu similar to our other menus to select a measuring type.

Feat - Ruler options added: 5-10-5 and euclidean.

---

Fog.js

Was applying this to all instead of just diagonals.

Beta Fix - 5-10-5 should be diagonals only

---

Fog.js

I also forgot to count diagonals in between segments.

Beta Fix - 5-10-5 count diagonals when non-diagonal segments are inbetween

---

Fog.js

Another issue where number of diagonals was stacking with cumulativeDistance

Beta Fix - Another issue with tracking number of diagonals 5-10-5

---

ScenesPanel.js

Took these out but no reason to after thinking on it.

Beta - put original manual grid settings back in

---

Fog.js

Remembers the last ruler selected so next time you load into above it's the same.

Beta - remember last ruler selection

---

Fog.js
Token.js

Reduce loops even further. Remove some checks when unnecessary.

More improvements to light performance

---

Main.js

This should be checking if it's not null.

Beta fix - center zoom on scene creation

---

Journal.js
TokenCustomization.js

There was an error when a parent folder was deleted for journals as sub folders wern't being deleted. Also deletes custom statblocks when the token is deleted.

Beta Fix - Deleting Subfolders when deleting a journal; Delete custom stat block when token is deleted.

---

CharactersPage.js
CombatTracker.js
CoreFunctions.js
Settings.js
Startup.js

Move the tab communication posts to after window vars get defined.
Fix button for custom pc blocks.

Beta Fix - get dice sent from pc sheets working on first load; Fix non-campaign pc sheet button in combat tracker

---

CharactersPage.js
CoreFunctions.js
DiceRoller.js
Main.js
Startup.js

various issues with the new dice rolling from non-campaign pcs. A few errors that have been around for a bit and load in the context menu css for pc iframes.

Fix - pc iframe context menu and other dice roller issues

---

Fog.js

This should improve light/fog performance further

Beta - More improvements for light/fog

---

CharactersPage.js
Main.js

On our to do list - swaps dom events for observer. Moves a bunch of the character sheet ones into the character sheet observer we already have.
Closes #970

Swap from deprecated dom events to observers - might be some performance improvement for some

---

Main.js

this should be toggle sheet not open for their own sheet button.

Beta Fix - Players own sheets should still toggle normally.

---

CharactersPage.js
DiceRoller.js
Startup.js

This should fix complex rolls expressions in iframes and others tabs

Beta Fix - complex roll expressions (eg 1d20+1d6+1) in notes of pc sheets 

---

Main.js
Startup.js

Saves and sets the last selected send to default option.

QoL - Save last selected send to default options (per campaign)

---

DiceRoller.js

this should be if no sendtotab is set roll normally.

Beta Fix - abovevtt note button rolls when no above tab is running

---

Token.js

Still trying to track down that token jumping error that happens occasionally.

Internal - Make sure these are parsed in case ones a string.

---

CharactersPage.js
DiceRoller.js
MessageBroker.js

Initiative wasn't being capture by some of the new rolling.

Beta Fix - initiative capture for rolls captured from pcs.

---

CharactersPage.js

oops only should have changed initiative

Internal - Only initiative needed to be changed

---

CharactersPage.js
Settings.js
Startup.js

More roll fixes for iframes and disabled ddb dice

Beta Fix - more roll fixes.

---

SidebarPanel.js

Display cr and book in the listing for convience

QoL - CR and book on the item list for open5e monsters

---

MessageBroker.js

Updates pc rows on scene swap to update their button.

Fix - Update pc locate/add button on scene swap

---

Token.js

Tokens aren't always syncing on delete lets make sure we send the message.

Fix - ensure tokens are synced on delete

---

Fog.js

Fixes 0 darkness walls and vision range.

Beta Fix - zero darkness shouldn't require tokens to be in darkvision/light range to see. Should act like global illumination.

---

Settings.js

with new grid stuff the current scene export wasn't sizing correctly.

Beta Fix - Current scene export correct grid size

---

SceneData.js

Map data for a ghost of salt marsh map

Map data - GoS 4.1 Emperor of the Waves by FuzzyBunny

---

SceneData.js

A community member Weasel Wargaming has offered his public maps to be available in abovevtt 🥳

Map Data: New community creator maps from Weasel Wargaming

---

SceneData.js

Moves weasel wargaming above youtube.

Internal - adjust order of community maps

---

Fog.js

Better logic for drawing vision.

Beta - Eliminate some unneeded draws for vision

---

abovevtt.css

QoL - Add slight door opacity so you can see map indication if it's locked or secret.

---

TokensPanel.js

The variable removeAllButton is undefined lets look for the button instead and show/hide it.

Fix - remove all custom image button wasn't displaying on added an image due to undefined error

---

TokensPanel.js

This is in addition to the last PR adding the custom images to the listing.

Internal - also set token panel image to default on remove all 

---

Fog.js
MessageBroker.js
ScenesPanel.js

Trying to eliminate as many 'loading into black' issues as possible.

Beta Fix - apply zoom after canvas reset; QoL - reset zoom on grid wizard so any scale changes don't throw you into black

---

TokensPanel.js

Removing an image was erroring on pc tokens - this selector fixes that.

Beta Fix - better selector to avoid error with pc listing

---

ScenesHandler.js
ScenesPanel.js

I had the fix wrong for this - it just fixed itself on refresh due to the migration happening then.

Fix - issue with fog not stay on map if a custom url was created and saved before refresh/migration

---

CoreFunctions.js
MessageBroker.js
Startup.js

Also clean up an accidentally left in line.

Internal - move these to startup so they don't run before initialized

---

Fog.js

Lets only render the redraws once finalized. Also when right clicking to drag the map lets not call a redraw.

Performance improvement with various redraws and while dragging the map with draw menus open.

---

manifest.json

bumps manifest for potential hotfix

Hotfix bump 1.0.1

---

Fog.js

Accidently changed drawings and light to true when I split them.🤦‍♂️

Fix - issue where border drawings were being filled.

---

manifest.json

Bump - 1.01

---

Fog.js

text is too large since zoom wasn't set.

Fix - text appearence when loading from another scene.

---

Main.js

I think this should solve the problem - I think these were triggering before the item existed for some people. I don't start the observation until the item exists now.

Fix - mutation observer bug due to item not existing yet

---

CharactersPage.js

I believe this fixes the not being able to roll after the first - I think in some cases the experimental setting may have been undefined.

Fix - Not being able to roll dice after 1st roll issue.

---

CharactersPage.js

Player owned extras when dropped by players.

Make player dropped extras player owned.

---

CharactersPage.js

Qol to not open the sidebar and there's a potential accidental name removal if customize is expanded.

Beta Fix - adding an extra token shouldn't open the sidebar to avoid accidental changes.

---

CharactersPage.js

set hidden to false for extras tokens

Beta Fix - player dropped extras tokens set hidden to false

---

ScenesPanel.js
Settings.js
Startup.js

Clears out some unused local storage data. Removes a never used function as we replaced it with a better version.

Chore - clean up some unneeded local storage and functions

---

ScenesPanel.js

UVTT is trying to be validated as an image causing some confusion.

Fix - Show url is ok but validation is not available for UVTT scene urls. (show ? instead of x)

---

Token.js

This should check the walkable area when we move the token rather then relying on it being correct on creation.

Fix - another issue that causes tokens to fly off.

---

Token.js

Fixes arrow key movement for groups.

Fix - token groups should be selected when a token in a group is selected.

---

Token.js

This adjusts dragging to keep the token closer to the cursor if you zoom mid drag.

QoL - Token should stay closer to cursor if zoom is changed while dragging.

---

Fog.js

Improves performance when drawing walls by eliminating redraws.

QoL - improve performance when drawing walls.

---

Fog.js
abovevtt.css

example: https://cdn.discordapp.com/attachments/1163068788833525770/1164177061611569193/2023-10-18_08-23-23.mp4?ex=65424360&is=652fce60&hm=3e475c9dd10b7035249e48b133bad0d3f943257f7a6f2d58b45a5fbf24aab730&

Beta - door visual adjustments

---

Fog.js

https://github.com/cyruzzo/AboveVTT/assets/65363489/cec8fa61-e0d9-4dea-9010-8d8c47009cd1

QoL - get main menu tools working with touch on some devices (ruler, drawing, fog, light etc.)

---

TokenMenu.js

Title row shouldn't have an index and occasionally erros.

Fix - issue where light preset edit window wouldn't open

---

Text.js
abovevtt.css

Adds a before element on top of the text area with the same text so it only appears to expand outwards

QoL - text stroke preview should be more accurate, it should only appear to expand outwards

---

Fog.js
TokenMenu.js

Fix - issue with doors/windows sometimes not being able to open the context menu

---

TokensPanel.js

Fix - issue with token images not being changable on tokens placed on the map

---

CoreFunctions.js
Main.js
ScenesPanel.js
audio/mixer.js

Switch the thumbnail links seems to resolve most of the issue.
There's still some issues with a large number of audio files loaded into the mixer.

Beta fix - more fixes for google issues

---

Fog.js
MessageBroker.js
Token.js
TokenMenu.js
abovevtt.css
audio/mixer.js
audio/ui.js

Adds audio token options - has range, attenuation options and blocked by walls option.

Audio tokens

---

Fog.js

Fix - error when darkvision/light is 0 and devilsight/truesight is enabled

---

CharactersPage.js
Main.js

Fix - issue with character sheet scrolling outside the primary action box

---

Main.js
ScenesPanel.js

Fix - issue with scene not updating player view on settings change when they were individually pulled to the scene

---

Journal.js
Main.js

Updated so that Chapter Folders with only DM notes are not shown to players.

QoL - hide journal folders for players if they don't have access to any notes in them

---

CombatTracker.js
Main.js
Settings.js
Token.js
TokenMenu.js
abovevtt.css

Currently token age option is only available prior to placing a token similar to hp roll.

Feat - condition timers and token age option 

---

Settings.js
Token.js

This is an alternative (adds to) previous PR by cleaning up the color choice code.
I'm not sure why it was doing all that parsing work - but maybe there is something I don't understand.
This is only spot checked for testing - but seems to work.

Cleaner code for color choice

---

Fog.js

This should give nice fadeout animations, whilst allowing for frameskips if overloaded

refactor: replace setInterval with replaceAnimationFrame in fadeout

---

CoreFunctions.js
Main.js

This might be a cool feature to have separately later.

Beta Fix - snap to grid should not be applying to projector mode when zoom lock is enabled.

---

CharactersPage.js
Main.js
Startup.js

Includes back up that looks for the gamelog svg path data and it's respective button. In case classes change again.

Fix - issue with gamelog not appearing for players due to DDB class change.

---

CharactersPage.js
MessageBroker.js

Started on this - may not get to finish testing/working on it until the new year.

Fix - some Beyond20 conflicts and failed pending messages.

---

CharactersPage.js
DiceRoller.js

Beta Fix - allow + at the start of added roll inputs

---

audio/track.js

Slight update to the previous audio updates. 
This allows for multiple exact searches, using AND logic. 
For example, here I filtered on a tag
And here, I further limit the list with a second tag.

add support for multiple exact AND searches

---

CharactersPage.js

DDB changed the player portrait from a background-image to an <img> tag.

Fix - issue where player img wasn't being picked up due to DDB changes

---

CoreFunctions.js
Token.js

Remove unused data from PC tokens

---

AOETemplates.js
CharactersPage.js
CoreFunctions.js
Startup.js

QoL - support aoe buttons in player tabs not in abovevtt if abovevtt is running in another tab

---

KeypressHandler.js
Settings.js

Style scrollbar for hiding when setting is selected and also during shift-H hide screen.
(Note only brief testing... given that scrollbar seems to act differently on different platforms/browsers)

Option for hiding scrollbar and during observer mode

---

CoreFunctions.js
Main.js

Zoom debouncing experiment.
Also adds touch zooming at the point between the pinch.
Mostly for test - not sure it's finished. Need to validate approach on other platforms.

QoL - Zoom improvements for touch screen, hotkeys when held, and complex scenes/low power devices

---

safari/build.sh
safari/iOS (App)/Info.plist
safari/macOS (App)/Info.plist

Merge when you get a chance.
No functional changes on existing - only affects future safari building

tweaks to safari build

---

KeypressHandler.js

Fix from window to local scope.
Get rid of misleading declaration.

Beta Fix - issue where ctrl still stuck on changing windows

---

CombatTracker.js
Token.js
abovevtt.css

This feels like the least layout affecting or odd one out option. Will see what else we can come up with though. Closes #3005

QoL - combat tracker option to highlight selected tokens

---

CoreFunctions.js
Main.js

afaict this will now be correct for Mac if you want menu to be platform specific

help menu improved for mac

---

EncounterHandler.js
MonsterStatBlock.js
StatHandler.js

Data for initiative has been added to the monster api, and spell tooltips seem to have been corrected for 2024.

Swap inititative and spelltooltips back to API data now that it's correct

---

AOETemplates.js
CombatTracker.js
CoreFunctions.js
Fog.js
MessageBroker.js
PeerCommunication.js
ScenesHandler.js
Token.js
TokenMenu.js
abovevtt.css

(NO HURRY!)
How do we feel about this feature:
Originate a new AOE at a token instead of middle of view  (only if a single token is selected).
This make it easy to select your wizard, cast the spell (add AOE on the caster) and then move the AOE to range while seeing the ruler and area.
PR is just a start - would love it if cone actually worked too... but some fair bit of geometry not worth it if no one likes this.
https://www.dropbox.com/scl/fi/z4gt3pow5jtp7j2eqaa0b/AOE-on-Selected.mov?rlkey=8pg3qyqlbefmjzz8icobbzfbs&st=g2syex0h&dl=0

AOE origin at single selected token

---

AOETemplates.js
Token.js

Addresses the ruler part of #3015 
This puts the drag ruler at point of origin for aoe to help with measuring distance when casting.
I decided to put square at an edge instead of center to help find max distance castable. 
Example:
https://github.com/user-attachments/assets/202e95a3-7b7c-4b54-a6b5-deffac16f5c6

QoL - draw aoe rulers from point of origin (on side to help measure max distance placeable for square)

---

AOETemplates.js
CharactersPage.js
Startup.js

Beta Fix - placing aoe at single selected token from player view or tab/iframe

---

CombatTracker.js
MessageBroker.js
Token.js
TokenMenu.js
abovevtt.css

Fix - several issues with combat tracker not behaving as expected especially with combat groups

---

.github/workflows/safari-release-build.yml
safari/README.md
safari/Shared (App)/ViewController.swift
safari/build.sh
safari/upload_secrets.sh

A few more fixes to safari build and workflow.
One small bug fix to container app to pass apple review.
Merge when possible - no functional changes.

bug fix for app store submission and build fixes for version

---

.github/workflows/safari-release-build.yml
safari/connectapi.py

safari build only: workflow option and script to push workflow builds to test flight testers

Feature safari push to testflight

---

CharactersPage.js
CoreFunctions.js
Fog.js
KeypressHandler.js
Load.js
Main.js
MessageBroker.js
MonsterStatBlock.js
PeerCommunication.js
SceneData.js
Token.js
ajaxQueue/ajaxQueue.js
peerDice.js
peerVideo.js

let -> var
This prevents google chrome crashes when a variable declared with let at global context is changed - I assume this a bug as this was working for a very long time.

Fix - google chrome crashes when a variable declared with let at global context is changed after a breakpoint in the dev tools

---

safari/connectapi.py

Safari deploy only: Seems to be a known problem that Apple call sometimes fails.  Implemented retries.

retry add to testers group when fails

---

KeypressHandler.js
Settings.js
SidebarPanel.js

Feature for consideration:
Custom die rolls on 8 and 9 key settable from UI Settings

custom rolls for 8 & 9 key

---

Token.js

Fix - issue where players could drag restricted access tokens that are not grouped if selected

---

Main.js

QoL - disable right click context menu in the areas around the map when dragging the map

---

abovevtt.css

Fix - issue where condition icons would be out of position after map changes

---

CombatTracker.js
CoreFunctions.js
EncounterHandler.js
Fog.js
Journal.js
MessageBroker.js
MonsterStatBlock.js
SceneData.js
ScenesPanel.js
Settings.js
SidebarPanel.js
Startup.js
Token.js
TokensPanel.js
audio/mixer.js
peerDice.js
peerVideo.js

The campaign page for ... in loops go through their functions  use for...of or i=0, i++

Beta - several more fixes for DM view

---

Journal.js

Fix - issue when sharing a folder it doesn't send the notes inside it to players until refresh

---

TokenMenu.js

Performance - default  door types vision to off for minor performance improvement
