- CombatTracker.js
- abovevtt.css
Moved most of the style "as is" from js to css.
Also removed the `height: 20px` when the element is hidden. If it is hidden it doesn't matter how tall it is. 
This refactoring includes also a minor logic change: it will add a class to the element rather than adding inline css.
>  [css-refactoring/combat_tracker] Move style from js into css.

- Main.js
This PR adds the ability to zoom into the map with ctrl+scroll (or pinch zoom on mac trackpads).
It also refactors the three zoom functions into one "change_zoom" function.
The event has to be set as `passive: false` to prevent the browser zoom from changing at the same time.
> Add scroll zoom

- Fog.js
- Token.js
Made the waypoint lines thinner and slightly transparent, added markers for each waypoint segment and fixed a bug for maps with an offset where snapping to grid wasn't accurate.
NOTE: This needs further work so the line tracks the centre of the token properly similar to Roll20 but I just don't have time to fix that. Most of the work is done in Fog.js WaypointManager class and the mouse handlers in Token.js
> Measure and Token Drag Cosmetic Enhancements

- PlayerPanel.js
Deactivated players probably shouldn't show up in the pcs panel. This becomes a bigger issue if you have a campaign with a number of rolling players.
> only display active pcs in player panel

- abovevtt.css
Intended behavior:
-When the mouse cursor is above a token, change the cursor to the 4-way cursor, otherwise revert to existing cursor settings.
-If the token is set to "lock token in position", keep the default cursor
-If a position locked token is attempted to be moved, give the nope :no_entry_sign: cursor (as default with jquery draggable)
> Add 4-way cursor when mouseover tokens

- Main.js
- MonsterPanel.js
- Token.js
- abovevtt.css
1. Allow users to set a default custom image for monster tokens. When a monster token that has a custom default image is placed, the custom image will be used for the token instead of the default DDB image.
2. Allow multiple images for the same monster. When a monster token that has multiple custom default images is placed, one of the custom images will be selected randomly and used for the token instead of the default DDB image.
3. Allow users to remove individual custom images that has been added.
4. Allow users to easily remove all custom images, effectively reseting the monster back to the default DDB image.
5. Allow users to easily switch between the custom images from the token contextMenu
1. Replacing the image for a monster every time you place it becomes tedious over time. …
> Add ability to set default custom images for monsters

- Fog.js
- Main.js
- Token.js
This adds the ability to rotate selected tokens. Here's a breakdown of everything that was added:
1. When you select tokens using the select tool, a bounding box will be drawn around the selected tokens. On the top side of that box is an eye symbol that can be dragged around. 
2. When dragging the eye symbol, all selected tokens will rotate to face wherever you drag that eye symbol to.
3. Holding shift while dragging the eye symbol will rotate tokens at 45º angles.
4. Rotations happen in real time for the DM, and are sent to players when the DM releases the eye token. This is to help with performance.
This is a DM-first feature because it is only available while using the select tool. My understanding is that the select tool will be going away, and players will be able to select multiple …
> Allow rotation of selected tokens

- abovevtt.css
This changes the way non-square token images are handled.
On the left is how it's currently handled, and on the right is with `object-fit: contain;`
> preserve token image aspect ratio

- Main.js
This adds a close button to the top right of the splash screen. It also closes the splash screen if you click anywhere outside of the splash screen. Here is a screenshot of the splash screen with the close button in the top right corner.
> add close button to splash and dismiss on any mouseup

- KeypressHandler.js
- Main.js
- Token.js
1. Add key binding for ctrl+c and cmd+c for copying tokens
2. Add key binding for ctrl+v and cmd+v for pasting tokens that have been copied
3. Ignore ctrl+c and ctrl+v bindings on Macs since they use the command key
4. Pasting tokens places the new tokens with a positional offset of half the token size down and to the right.
5. After pasting tokens, the selection automatically changes to the new tokens to make it easier to move them 
6. After pasting tokens, the paste buffer is updated to the new tokens so that pasting multiple times has a cascading effect instead of stacking them all on top of each other.
DM on the left, Player on the right
https://imgur.com/a/w73cOJr
> Add copy paste for tokens

- Token.js
This changes the multi-selection context menu for players, and removes a few unnecessary dividers.
> context menu cleanup for players

- Jitsi.js
- MonsterPanel.js
monsters with long names are causing broken tables in the monster panel
> limit monster entry width

- PlayerPanel.js
Set the scroll position back to where it was after repopulating the character list for games with many characters.
> Remember character list scroll position

- MessageBroker.js
Previous method would only examine 50% of the array; while loop will not work in current format with popping the message back onto the stack on the end without adding a var just the same due to pop() back onto the array if !found.
> Simple fix to retain length instead of re-calculating per loop

- Fog.js
- Main.js
- abovevtt.css
Add brush tool, gets the mouse position every 75ms to keep the number of points fairly low while still providing good tracking.
Add line-width slider for draw tools, works with the brush, lines, and any 'border' shape.
Made functions for drawing each shape to cut down on repeated code in drawing_mousemove, redraw_drawings, redraw_canvas.
Changed drawing_mousemove so the shape looks like what it will be while drawing, rather than always being red and transparent.
("Filled" and "Border" shapes are 90% opacity while drawing).
Adding fog now creates a grey shape as it is being drawn. Revealing still creates a red shape. This makes it less likely for DMs to mix them up as they are using them.
Right clicking while drawing shapes/fog will now cancel the draw.
Middle-clicking will no longer end a …
> Brush tool, line thickness

- Token.js
Bug: If the TOKEN button in the player list is clicked for a player who's token is already in the scene, the token will be re-placed in the middle of the scene for players, but the DM will not see the token move.
Fix: The TOKEN button will check to see if the player token already exists, and if so it will be highlighted for the DM.
> Bugfix: Player token re-placed if token button clicked

- Main.js
Bug: If a campaign has any public notes, all players can see the "JOIN AS DM" button.
Fix: look for .ddb-campaigns-detail-body-dm-notes-private instead of .ddb-campaigns-detail-body-dm-notes-label to determine if the JOIN AS DM button shows up
> Bugfix: Hide DM button for non-DM

- Main.js
BUG: If preload_player_sheet hits a bug it fails the extension, this is noticeable if you have a non-campaign owner DM acting as DM and a player has their sheet to private (for example). When it calls getPlayerIDFromSheet the variable is undefined causing a barf which prevents parts of the module from loading completely.
FIX: If the player sheet url is undefined, return a -1 player id (distinct from a 0 player ID for the DM)
> BUGFIX: Exception For Private Character Sheet

- Token.js
I often find myself subtracting the damage the players deal before checking the monsters hp to see if it would kill it, resulting in that final blow dropping the monster into the negative rather than `0` and killing it. This causes me to adjust the hp twice twice.
Either way, I don't believe hp (or max hp) could ever be negative in 5e, this change fixes that by forcing `0` as the maximum for either hp or max hp. Final blows greater than the monsters current hp will correctly result in it dieing and receiving the big red ❌  instead if it dropping into negative numbers and still "looking" alive.
> prevent hp and max hp from being negative

- Token.js
Check if a scene has been loaded before trying to place a token
> BUGFIX: Place Token In Unload Scene

- Jitsi.js
The Fullscreen icon was disappearing when clicked, now it properly switches to the fullscreen_exit icon and back properly
> BUGFIX: Jitsi fullscreen button icon fix

- PlayerPanel.js
Currently we're getting the PC images from the thumbnail of their character sheet, but this is a low quality version of the image. You can get the high resolution image by removing the `/thumbnails` and `/60/60` part of the url. (The numbers change depending on the character)
This is admittedly slightly hacky, but I can't see a better way of getting the high quality image at this time, and it makes a huge difference to the look of the VTT.
> Use higher resolution images for PC tokens

- Jitsi.js
* added share audio feature (for sharing your computer's audio, a just a tab, etc)
* added share desktop feature (for sharing something quickly from your desktop, a tab, etc )
* added select background feature, for hiding the giant mess behind you
* moved deprecated `TOOLBAR_BUTTONS` options to `configOverwrite` object
* on video layout toggle, force the tiling state rather than toggling it
* fixed event listener workaround
* fixed bug where jitsi was being bottomed when not being asked to 
* general code cleanup
* fixed width overflow
* width before
*  width after
> jitsi improvements

- PlayerPanel.js
fixed an issue with thumbnail images not upscaling if their url where the first two numbers are also 2 digits
Thanks to Anominous#6048
> BUGFIX: High res avatars

- Settings.js
- Token.js
- TokenMenu.js
- abovevtt.css
This does 2 things:
1. token images are no longer stretched to fill the space. This allows non-square images to be used.
1. a new setting has been added to allow existing users to switch back to the legacy behavior which stretches non-square images to fill the space.
I used `object-fit: contain` rather than `object-fit: cover` because images that go outside the token div get cropped when using `cover`. I couldn't figure out how to allow the images to `overflow` properly so I opted for `contain` instead. If we want to allow images to overflow, I think we might need some HTML restructuring. I can try to figure that out if that's the route we want to go, but I wanted to keep the changes to a minimum.
The boat on the right side is a custom token.  
The image on the left is with the legacy …
> support non-square token aspect ratio, add setting for legacy aspect ratio handling

- KeypressHandler.js
- Token.js
This allows holding shift and pressing an arrow key to rotate selected tokens. It only supports cardinal directions because Mousetrap can't handle multiple arrow keys at the same time.
> rotate tokens with shift+arrow keys

- Main.js
- MonsterPanel.js
- Token.js
- abovevtt.css
This completely overhauls the custom token image experience. It drastically improves the UI, and makes all the interactions much cleaner and easier to understand. It's still a _relatively_ hidden feature, but I added some information when accessing it via the context menu that should help with discoverability.
Custom image configuration now uses a modal instead of a context menu. This can still be accessed by right-clicking the image on a monster row, but can also be accessed by clicking the button on the right side of the monster row. This modal can also be accessed for a placed token, via the token context menu. When accessing the modal for a placed token, there are extra options for setting the image on that token without saving the image for other tokens. …
> Improve token image customization UX

- Main.js
DDB's scripts call a function named processFlashMessages every 2500ms.
The function runs on the main thread for a very long time - profiling shows it takes about 200-250ms.
If we're during 'animation' - i.e. drawing, selecting, measuring with the ruler etc. - the function call introduces a noticeable stutter as new GPU frames are stalled.
This patch hooks their function and avoids calling it while the mouse button is 'down', only if the message received as argument is "FlashMessageAjax".
> Hook DDB's processFlashMessages function to avoid calling it during animations

- KeypressHandler.js
- Main.js
- MonsterPanel.js
- Token.js
- TokenMenu.js
- abovevtt.css
* Complete rebuild of the tokens pane to mimic the monsters pane UI
* Custom tokens can now be edited
* Custom tokens now support a specified size
* Custom tokens now support multiple images just like monsters do
* Placing a custom token that has multiple images will choose one of the images at random
* Custom tokens can be drag and dropped from the list to the map
* Custom token images can be drag and dropped from the customization modal to the map
* Custom tokens and their images both have context menus for edit, delete, and placing options
* Folders can be renamed
* The context menu for a placed token have a "Change Image" option instead of an inline url input. This opens a simplified token customization modal.
* The simplified customization modal allows adding a url for just the …
> Tokens pane rebuild

- Main.js
- ScenesHandler.js
* Added an error message in-case loading a map image failed
* Added an error message indicating the map size is too large for the user's browser
* Added an error message indicating grid square sizes resulted in upscaling of the map, resulting in exceeding browser canvas limitations
> Error handling for map loading issues and exceeding browser max canvas size

- Token.js
This adds the ability to change the AC of a monster token via the context menu. The value is only set if it can be parsed to a number.
https://trello.com/c/V2DE3ywb
> add monster AC to context menu

- Main.js
- MonsterPanel.js
- PlayerPanel.js
- Token.js
- TokenMenu.js
https://trello.com/c/XCPdCfm2
This adds custom token images for player tokens. Player tokens can be customized by right-clicking the token image in the Players pane. 
**Token Context Menu**
If the player token has not been placed, the context menu has four options: "Place Token", "Place Hidden token", "Copy Url", and "Customize". Once a token has been placed, the place token options are replaced with "Locate Placed Token".
**Drag and Drop Token Placement**
Player tokens can now be placed on a scene, by dragging the player token image onto a scene and dropping it where you want it placed. If a token has already been placed on a scene, the token will not be placed, but instead will highlight the already placed token.
Just like the monsters modal, player tokens now support multiple images. …
> Add player token customization

- Main.js
- MessageBroker.js
1. On 'playerjoin' message, players will now send their AboveVTT version as well
and character ID.
2. The DM will save all of these, and alert in case it detects some players
are running a version older than the newest one seen yet (message broker
doesn't send us the latest available version, so we can't use that).
Backwards compatibility is handled by popping up a message saying
a player connected with an older version than 0.64 (as 0.65 will include
this change) and avoid popping up messages too fast (interval 3 seconds).
In addition, we don't re-pop alert message if the same player reconnected
without any change to its AboveVTT version.
> Add alert message indicating players/DM aren't running latest version

- Fog.js
Prior to this fix, when using the selection box, players could select
hidden tokens by mistake and move them. In addition, that would have caused
the token to be unhidden.
> Bug fix: don't allow players to multi-select hidden tokens and move them

- Load.js
- Main.js
- MonsterPanel.js
- PlayerPanel.js
- SidebarPanel.js
- TokenMenu.js
- abovevtt.css
- manifest.json
This is functionally equivalent to the `main` branch. I added `SidebarPanel.js` which drastically cleans up token modal construction. I also updated the tokens tab to use it since it already had the same structure. As we start to clean up the other sidebar tabs, we can migrate them to use `SidebarPanel` as well. Then all of our sidebar tabs will have a similar structure and look. I didn't update any tabs in the PR because I wanted the scope of this PR to be a refactoring of those that already use this structure.
> add SidebarPanel.js and refactor tokens pane and all modals to use it

- Main.js
- SidebarPanel.js
- SoundPad.js
- abovevtt.css
This nests the sounds tab content inside of a `SidebarPanel`. It also cleans up a few id collisions with the tabs, and a little CSS for the tabs.
> update sounds panel to use SidebarPanel

- Settings.js
- SidebarPanel.js
This nests the settings tab content inside of a `SidebarPanel`
> update settings tab to use SidebarPanel

- Main.js
- abovevtt.css
* Remove a weird border from the SidebarPanel. Not sure how I missed that before, but it's gone now.
* Add a bit of padding to the `SidebarPanel.body` so things aren't right up against the edge.
* Color the tab button to match the background color (white for gamelog, blue for the rest)
> quick sidebar CSS tweak

- ScenesHandler.js
- Settings.js
- SidebarPanel.js
- TokenMenu.js
- abovevtt.css
This is a UI update to the settings tab. 
1. It updates the style of the import / export section
2. It converts the checkboxes to a toggle that mimics the DDB content sharing settings. 
3. It adds descriptive hover text to all the settings and import / export buttons
4. It adds example tokens that get updated as settings are changed to better show what all the settings do.
> update settings panel UI with example tokens

- Main.js
- MessageBroker.js
I found one way to reproduce the "Send to Gamelog" bug
Make a `Rock Gnome` character, and then press the "Send to Gamelog" button on the Racial Feature `Artificer's Lore`.  
The console log gives this error twice:
```
_dndbeyond_message_broker_client.00a081b659ffc6309334.bundle.js:16 Uncaught SyntaxError: Unexpected token  in JSON at position 1780
at JSON.parse (<anonymous>)
at t.<anonymous> (_dndbeyond_message_broker_client.00a081b659ffc6309334.bundle.js:16)
at t.triggerHandler (_dndbeyond_message_broker_client.00a081b659ffc6309334.bundle.js:1)
at _dndbeyond_message_broker_client.00a081b659ffc6309334.bundle.js:1
at t.postSync (_dndbeyond_message_broker_client.00a081b659ffc6309334.bundle.js:1)
at t.postOrPostAndWait (_dndbeyond_message_broker_client.00a081b659ffc6309334.bundle.js:1)
at …
```
> sanitize HTML being sent over the websocket

- Main.js
- MonsterDice.js
This parses sidebar stat blocks, and injects dice rolling abilities just like we do for monster stat blocks. I also added the ability to right-click the buttons which displays a modal like DDB does. The modal contains the following options:
* Send To: [Everyone|Self] (DM only)
* Roll With [Advantage|Flat|Disadvantage] (only for "to hit" roll types)
* Roll As [Crit|Flat] (only for "damage" roll types)
> Allow rolling from player sidebar stat blocks

- Fog.js
- ScenesPanel.js
Minor 2D rendering optimizations - when drawing lines, we should draw all before stroking.
> Optimize some 2D line rendering

- Main.js
- MessageBroker.js
- abovevtt.css
~The fix is generally pretty simple. After validating that a string is a URL before injecting it to chat, there was no handling for if  the string was a non-image url. I've added an additional bit of logic to determine whether the link is to an image or not, and generate an `<a>` tag instead of an `<img>` tag if it's not an image type.~
~I've included the most common image types in my additional logic, but if another needs to be accounted for, it's easy enough to add.~
I've gone with an alternative approach to the original. If a link is detected, we try to load an image tag with that link, if the image load succeeds, we create an image tag, otherwise we create an `<a>` tag.
Note: I'm using string interpolation to construct the `<a>` tag, I've not seen that much elsewhere in the code, so …
> Fix chat log links being converted to images.

- Main.js
- MessageBroker.js
- MonsterDice.js
- abovevtt.css
This attempts to parse rpgDiceRolls to DDB format before sending them over the websocket. If the parsing fails for any reason or if the expression is too complex, it falls back to the old way.
I've also started injecting a "Send to Everyone" button into gamelog messages that were sent "TO: Self". This works for our rolls as well as for DDB dice rolls. The following gif shows an  rpgDiceRoll followed by two DDB rolls from the mobile app. The first is "to self" and the second is "to everyone" to show that it doesn't inject the button for those rolls.
> Convert rpgDiceRoll results to use DDB format

- Main.js
- MessageBroker.js
This PR further improves image handling in chat by initially posting the image link to the chat, then replacing it with the image if the image can be loaded. If the image can't be loaded, or the link doesn't point to an image, the link stays in place.
This ensures that the chat messages will maintain their order even if messages are being posted very quickly or the load time for an image is very long. This should also be more efficient since we're loading the image once and not loading a separate image in memory before creating the image tag (which would cause us to have to load the image twice).
> Image link async unfurling

- CombatTracker.js
I'm guessing this was either a copy/paste error or a merge gone wrong. Either way, it's a simple fix
> fix for combat stat button not working

- MonsterDice.js
This would throw an error and stop parsing if the monster didn't have an avatar image
> fix extras monsters not parsing when no image

- Settings.js
This PR is intended as a first step into the project. (See https://discord.com/channels/815028457851191326/832199739398946817/931271695560507423)
It adds the restrictPlayerMove option to the token settings options in the Settings tab.
The "Reset Token Settings to Defaults" button calls the click() of each toggle that is turned on, and the click of each toggle sets the corresponding setting to the new value (See Settings.js line 125, which uses the function defined in SidebarPanel.js line 224).
Before, it simply set everything to false.
Now, Reset Token Settings essentially does the same thing except for the "restrictPlayerMove" setting where it sets it right back to true. I removed the window.TOKEN_SETTINGS[name] = false for each toggle in the loop. It needlessly set them a second time …
> Add 'Restrict player movement' as a default token setting

- Token.js
Simple fix for readding double click conditions to send them to gamelog. 
Just adds it as text, I don't think we need any more than that(?)
> Fix for sending conditions to gamelog

- Main.js
- MessageBroker.js
DDBs web-socket may get disconnected due to various reasons,
and their current logic doesn't always manage to reconnect the
web-socket.
Added code that checks DDBs web-socket status and forces a reconnection
attempt when possible. This fixes issues with dice rolls not appearing and
other various issues which forced users to refresh the page in order
to get things working again.
The logic it runs is as follows:
1. Every 4 seconds (following an initial 15 seconds delay) check
if the browser is online, and if it is, check if DDBs web-socket
is in connected state. If it's note, force reconnect.
2. Every call to get_cobalt_token now does that same check, to ensure
we don't attempt to sent messages that won't arrive to the other side.
The force re-connect is protected by a best-effort lock …
> Monitor and attempt re-connection to DDBs web-socket

- TokenMenu.js
- abovevtt.css
Now that the Monster rows have been rebuilt, the custom tokens rows need to be updated to match.
Closes #216
> update custom tokens row UI to use gear icon

- PlayerPanel.js
- Token.js
Closes #220 
Rather than using the old `token_button` function, the "add party" button now calls the `place_player_token` button which already takes into account global configs, custom images, etc. I also added support for adding the player tokens as hidden if you hold the shift key when you press it.
> fix: add party button doesn't respect global configs

- Main.js
- PlayerPanel.js
There were some odd interactions with the DM card on the players panel. 
1. The DM card is no longer shown to the DM since it's useless for the DM to see it.
2. players can no longer drag and drop other player tokens (it never added the tokens, but they also don't need to be able to drag and drop them at all)
3. The DM would also get an iframe in the `#sheet` container which would never load since it's not a real character. This no longer happens
> clean up DM player card a bit

- PlayerPanel.js
If there is a private character in the campaign, there isn't a link to that character's sheet that we can use which means that `window.pcs` will not include a `sheet` for that character. That ultimately breaks things for all other players.
This protects against that scenario
> fix for private characters breaking the game for other players

- Main.js
We will now check for DDB's WS every 4 seconds (following an initial
15 seconds delay) and that's it - not everytime get_cobalt_token
is called.
> Remove force DDB WS reconnect in get_cobalt_token

- abovevtt.css
> fix : scroll bar no longer overlaps over dice in combat lag

- Journal.js
When embedding an image into journal entries, tinyMCE was trying to re-write certain urls (any image loading from dndbeyond domain) from absolute to relative.  This was causing players to not be able to see the image since the relative path is different from the player page vs. the dm page.  Adding a few lines to the tinyMCE init fixes this.
> Journal.js edit_note - add options to tinyMCE initialize to fix url rewrite bug

- Main.js
- MonsterPanel.js
- ScenesPanel.js
- SidebarPanel.js
Closes #222 
This updates the `parse_img` function to process dropbox links in a similar way to how it processes good drive links. It also updates the `ScenesPanel` to use the `parse_img` function instead of duplicating the logic of that function. While testing this change, I found a bug in the token customization where `parse_img` wasn't being called so I fixed that, too.
> add support for images hosted in dropbox

- MessageBroker.js
Users have reported an issue when using DDBs dice rolls where there's a chance
the roll will constantly be the same.
We believe the issue is when the tab loses focus, causing the dice roll
animation to stop. If enough time passes, DDB returns the previous value.
This attempts to fix this issue by hooking requestAnimationFrame
ONLY during dice rolls and replace it with setTimeout - these are used by DDBs
rendering engine to draw the dice rolls.
Browsers tend to stop respecting animation frames requests on focus lose,
whereas setTimeout will continue working.
NOTE: setTimeout may introduce stuttering in rolls animation as for rendering,
as requestAnimationFrame is the preferred way.
1. When we receive a pending dice roll message, we hook it ONLY for the user who initiated
the roll.
2. When …
> Fix possible constant dice rolls

- AOETemplates.js
- Main.js
- MessageBroker.js
- Token.js
- TokenMenu.js
This adds a new token option `deleteableByPlayers` which is checked when tokens are deleted. The only thing using it are AoE tokens since those are the only tokens that players can add to a scene.
AoE tokens were the only tokens still using the old `token_button` function so this also removes that function.
closes #263
> allow players to delete AoE tokens

- .gitignore
- MonsterPanel.js
I think we should temporarily disable drag and drop form a monsterPanel row. It is currently broken and leaves an img in the top left corner of the map until you refresh. Until a real fix can be implemented, we should prevent the bad experience.
This is not a solution to https://github.com/cyruzzo/AboveVTT/issues/287, so this issue should not get closed if this PR is merged.
> temporarily disable monster row drag and drop

- EncounterHandler.js
There was a bug with the logic of #286 where refreshing the page as a DM would delete your backing encounter. This fixes that 🤦
> fix for backing encounter being deleted on refresh

- EncounterHandler.js
When you refresh the page on the encounters page, we would create a new encounter unnecessarily. It would eventually get cleaned up when you launch again, but we don't need to be doing that.
closes #340
> stop creating encounters on the encounter page

- EncounterHandler.js
- Main.js
- MonsterPanel.js
closes #341 
1. reduce the risk of unintentionally creating or deleting encounters on refresh DM refresh
2. alert users that experience fatal errors during encounter handler startup
3. temporarily prompt users that may have a pop-up blocker. Most users will never see this, but those that get blocked, will.
> Improve encounter handler startup flow

- LoadCharacterPage.js
- manifest.json
I'm grouping those two things to make a single change to the manifest (we really need to keep these low in number).
First part of this PR will let abovevtt continue to work if DDB forces us to switch to the new url format for the character sheet.
Second part of this PR introduces a new file LoadCharacter.js . This new content script will let us add "join abovevtt" buttons to the character page and to the "my character list". 
This is needed to complete #300
> Support new ddb/character/[0-9]+ url for players. Add permissions to add buttons to the 

- MessageBroker.js
- ScenesPanel.js
- abovevtt.css
Closes #358 
I believe this also Fixes #384 
I believe the actual request once figured out on discord was to not have the scenes panel scroll up when selecting a new scene. So you can easily switch both players and DM.
https://user-images.githubusercontent.com/65363489/161395246-7b13a1ef-f946-434b-a021-0f047a4568a1.mp4
> Stop scroll when switching scenes and improve performance of scene panel

- EncounterHandler.js
found a weird bug with urls in which the large avatar url is saved onto the monster but it might be wrong. the last 2 sections of the url have to be 1000 otherwise it fails
shown it working
https://discord.com/channels/815028457851191326/815028804103307354/959469570110939156
> mon image shows even when homebrew

- Token.js
- TokenMenu.js
fixes #396 
Removed shortcutting "token owned by player" modifying other options. The DM now has more control over what the token does, so they could allow players to view a tokens sheet, but not show their hp/ac, or not allow them to move the token (this could be very cool if you have siege weapons or something like that)
Added enabled/disabled descriptions from token configuration menu as they were missing (the function had them as inputs though 😄 )
> Bugfix - for players owning tokens

- Token.js
@vlaminck confirmed that there was issues with a merge see https://discord.com/channels/815028457851191326/930926587392692335/964934545629663283
in regards to the context menu reverting changes.
This has now been resolved
Also sorted out all tokens having hp bars on them. By actually just adding in that feature, when tokens have "disablestat" disabled a DM can add hp/ac/elevation to a token via the context menu / by adding hp to the tokens hp bar
resolved issue where hidestat was also hiding for DM
fixes #405
> Bugfix - context menu reverting token options, health of tokens not right

- Main.js
Closes #388 
There was also a bug where the Undo button would pop twice instead of once. I think the click handler got duplicated during some merge conflict so I removed the extra click handler and now it works correctly
> fix drawing clear and undo not functioning properly

- TokenMenu.js
Some person was a bit confused as to why he couldn't add in a token 
https://discord.com/channels/815028457851191326/852495991227809802/965231200119709726
we didn't provide any feedback to say name was required. This resolves that
> added some user feedback so they know they have to specify a name

- abovevtt.css
Fixes #397 - I had some time to do a quick fix for this.
> Fix blurry context marker images

- ScenesHandler.js
Closes #332
I didn't test everything, but the reported examples work with this change. I also stopped handling these sources as special cases: `["gos", "wdh", "wdotmm", "llok"]`. By handling this more generically, the importer should be more robust.
> Fix: some map imports are broken

- CombatTracker.js
The remove from combat button in the combat tracker should now update the token combat status properly. 
fixes #413
> Fix: The remove from combat button in the combat tracker should now update the token combat status properly.

- abovevtt.css
This will align the buttons like the one on the right here:
Fixes #415
> Fix: Align buttons properly in the combat tracker for custom tokens and other tokens with fewer buttons.

- EncounterHandler.js
This should fix the sync issues with monster rolls again. This locks open the sidebar so the default menu is "clickable"
Fixes #417
> Fix: Repush the fix for monster roll syncing with default rolls.

- abovevtt.css
Left is chrome right is firefox. Fixes #431
> Fix: Styling of window buttons and round number in firefox.

- Main.js
The player monsters should no longer display the footer or open the marketplace. Fixes #433 
https://user-images.githubusercontent.com/65363489/164947235-bca9cfab-619a-4cfc-92df-11343b190f62.mp4
> Fix: Player monster iframe display issues.

- Main.js
Closes #427
This makes the player monster stat blocks moveable/resizable as well instead of static and covering most of the player area.
Edit: example video https://www.youtube.com/watch?v=-SjtevefyCY
> Add: In Player view monster stat blocks are now moveable/resizable

- Main.js
Fixes #429
This is setup to listen to the event first then stops the propagation of the throttle scroll event listener.
edit: Better comparison videos. It is more pronounced on my monitor than in the videos below but I can still see a difference in these with regards to smoothness.
Before:
https://user-images.githubusercontent.com/65363489/164948832-db056c26-d2f6-42d0-898e-aeb521201328.mp4
After:
https://user-images.githubusercontent.com/65363489/164948834-b4034f06-ae0f-4bc2-8cef-b365e44eb1ed.mp4
> Fix: for drag map lag in player view

- abovevtt.css
This fixes #436
https://user-images.githubusercontent.com/65363489/165018498-40eacbf6-405e-4039-ad80-01015e2de0c8.mp4
> Fix:  In DM view stop the player sheet from sliding to the side when the sidebar is closed

- CombatTracker.js
This now updates the token combat status properly when hitting clear.
Fixes #439
> Fix: Combat tracker clear button sets combat status

- Fog.js
- ScenesHandler.js
- ScenesPanel.js
- abovevtt.css
Adds colour picker and line width to edit scene dialog.
Allows live update of grid changes (color/width)
- General cleanup of edit dialog, moved away from checkboxes in favour of toggles like a bunch of other places #consistency
- Moved away from using 1/0 as input options (under the hood it's still 1/0 as to not break existing scenes)
- Added colour picker and line width inputs
- Cleanup of grid rendering
- Moved snap/colour up to the main block so now the buttons are more for scaling rather than all grid options
- Removed chunks from grid wizard that were overriding snap/grid choices
https://www.youtube.com/watch?v=IfRcMtsICFY
> Change grid colour and width. Scene edit form update with toggle buttons. Validate map urls on focussing out of those inputs

- ChatObserver.js
`href` is not valid on `img` tags, but magnific uses it. I'm sure it was removed because it's not valid on img tags so I added a comment to hopefully prevent this bug from coming back in the future
> fix for gamelog images not showing when clicked

- Token.js
- abovevtt.css
This checks which side is longer and sets that side's min-width to fit the token size if `ignore aspect ratio` is disabled. This ensures that a 1.0 scale image fits it's token size properly when the token is larger than the img src. It does this by stretching token images on the longer sides axis to maintain aspect ratio. 
Closes #483
> Fix: Set width or height of tokens that retain their aspect ratio to fit larger size tokens when the image isn't big enough

- Main.js
- Token.js
- TokenMenu.js
- abovevtt.css
Fixes #476 
Conditions will only show up in the context menu when no player tokens are selected.
A warning is added at the bottom of markers if a player token is selected.
> Fix conditions showing up when player token is selected

- Main.js
- abovevtt.css
First off Dndbeyond won't create tooltips on the monster page if the width of the window is <= 640. 
```
createTooltip: function (event) {
if (this.Disabled || !event.currentTarget.getAttribute('data-tooltip-href') || $(document).width() <= 640) {
return false;
}
```
The frustrating part is after they are created you can shrink the window down and they work fine. I just couldn't find a way to get it to create the stuff automatically. So if we had a way to have them created and then allow free resizing that'd be great but I couldn't figure that one out. 
I'm unsure if this is the route we want to take with the downsides but I can't think of how we'd go about different with getting the tooltips to show up in general not just in the iframe
Edit: Now fully fixes #482 
Both players and DM can …
> Fix: Tooltips for monster iframes.

- CombatTracker.js
- Token.js
- TokenMenu.js
Closes #487 
* This adds a `ct_list_tokens` function that collects and returns the tokenIds that are in the combat tracker. 
* It also adds a convenience function `token.isInCombatTracker()` to easily determine if a given token is in the combat tracker.
* All references to `token.options.combat` has been removed
> stop storing combat tracker info on the token

- ScenesPanel.js
Fixes #499
Grid toggles for scenes no longer will always show as on. This also adds the grid toggle setting to apply automatically to the DM view when toggled.
This does not fix the player view needing to be refreshed to take effect. Although the DM can just click players again to force a refresh it is not great for potatos. That can be a separate fix as that issue already existed.
> Fix: grid toggles will no longer always show as on

- KeypressHandler.js
- Main.js
- MessageBroker.js
- ScenesHandler.js
- ScenesPanel.js
- SidebarPanel.js
- TokenMenu.js
- TokensPanel.js
- abovevtt.css
Closes #508 
Closes #503
Closes #509
1. Move the list of Scenes into a new Scenes tab in sidebar utilizing the `SidebarListItem` framework that was added during the the Tokens Panel unification. 
2. Allow Scenes to be added to folders. (cannot be moved yet)
3. Allow Searching of Scenes
4. Refactored some of the `SidebarListItem` framework to be more generic and reusable.
5. This is only available if `window.CLOUD` is true. Non-migrated users will continue to use the old window at the top of the screen.
We discussed not showing images in the sidebar to reduce the initial download and memory impact. I chose to leave it in for now so we could all play with it before making a final decision on it.
https://user-images.githubusercontent.com/584771/169146013-16312f54-9bee-48ac-bcc4-e15684a925b2.m …
> Move Scenes list to sidebar

- CombatTracker.js
- TokenMenu.js
Fixes #496 
This will always add hidden tokens as hidden from players in the combat tracker.
> Fix: When a hidden token is added to combat it should now properly always default to being hidden in the combat tracker.

- Main.js
This updates the error message with more debugging messaging, as well as allows the user to open the image in a new tab. If the user is not the DM, it prompts again with a "SPOILER ALERT!" message since they might open the image without any fog of war. However, the map won't load so it's unlikely to load in a new tab either.
Here's a non-public gdrive link to test with `https://drive.google.com/file/d/1rboAWxZpr0SUlRp2MR5pd_EHAISgR-0z/view?usp=sharing`
> update error message when map fails to load

- Token.js
This fixes the selections boxes for wide or tall images when scaled outside their token. This was working at some point but I probably broke it in a recent fix for something else. This is a QoL fix since clicking dead air and having a token get selected isn't great. This minimizes that as much as possible again. Fixes #525
VS
> Fix selection hit box for tall or wide image tokens when scaled

- Journal.js
- abovevtt.css
Ensures for both Player and DM view that the note displayed doesn't leave it's window. 
Also adjusted the mce menu a bit to allow better resizing. The editor should also fill the window.
A small step towards the journal update in #391
> Contain large images in journal window - adjust menu

- Token.js
I feel 500ms is a better feel than 3000 for the fade timer. It feels like a performance issue at 3000 as mentioned by a few people.
> Fix when placing tokens feeling like a performance issue 

- Main.js
- MessageBroker.js
- Settings.js
- abovevtt.css
There's still a lot wrong with this but thought others could look at it and some wanted to see it. 
This works with firefox now. 
Some of the issues if anyone wants to tackle them - this will probably be pretty slow going for me:
<s>Addressing this somewhat I added new servers. They are free to use, can be used in I think all software but also open source projects. The connections seem to be more consistent and I no longer get errors requesting a STUN server (I added on from the same) More info here:
https://www.metered.ca/tools/openrelay/
https://www.metered.ca/tools/openrelay/terms-and-conditions</s>
I switched this to a google server as the aboveVTT turn and the one I found weren't working today externally.
I think there's probably more to fix but these are the main ones
> Fix dice streaming

- ScenesPanel.js
Fixes the darkness preview. It should now only show the preview when on the current map.
> Fix: darkness preview only if adjusting current map settings

- Token.js
- Disabled token measuring unless `window.ALLOWTOKENMEASURING` is true
- removed scroll as it messes up the cursor position while dragging tokens
- fixed issue in which a tokens waypoint would start from anothers if quickly changing tokens
> Disabled token measuring

- Token.js
Selection border fit's the token image boundaries. Below are examples of tokens that are not square or are scaled up.
> Draw selection box around non square token or scaled images.

- SidebarPanel.js
I set 
row.attr("title", `${listItem.name}\nclick to preview`);
so you can see the name when you hover and it also tells you "click to preview"
I then inject the preview when you click it. You can see the network tab on the left side loading the images as you click.
> move scene preview from hover to click

- ScenesPanel.js
- SidebarPanel.js
- TokensPanel.js
- abovevtt.css
- built-in-tokens.js
1. Don't expand folders all the damn time... Any collapsed/expanded folders should now stay that way when you reorder things
2. Allow dropping anywhere on the sidebar body to move things to the root folder. (not the header, though, just the body)
3. Add Expand All and Collapse All buttons
4. Move built in tokens to a dedicated NPCs folder
> folder improvements

- TokensPanel.js
This fixes a bug where fetching the encounter could get stuck in a loop. The problem was that we were fetching the encounter, then the monsters within the encounter, then trying to place those monsters. However, we weren't waiting for both fetch requests to finish which would just start the whole thing over again. This would loop until the monsters finally finished being fetched.
This fixes that bug by passing the `callback` to the monster fetch request, ensuring that both requests will finish before we move on
> fix: encounter monster fetching can loop

- ScenesPanel.js
- SidebarPanel.js
The sidebar doesn't know how to handle things that are named the same at the same folder path. This prevents saving scenes and folders if the name is already used. It will prompt the user at the same time.
> prevent scene naming conflicts

- ScenesPanel.js
It looks up the search value when the `did_update_scenes()` is called and filters the list if the scenes tab is active in the sidebar.
I also changed the input type to `search`, which will add a little 'x' to the right of the search box to clear the content.
This is a browser specific feature, but has over [97% browser support](https://caniuse.com/input-search).
This fixes https://discord.com/channels/815028457851191326/815028804103307354/988454588636078150
> Persist scene list filter through did_update_scenes()

- TokensPanel.js
> turtle_stew - AboveVTT: I'm unable to choose undead as a filter option for monsters. Probably because it is the last entry in the list?
>(No problem filtering when using the encounter builder via the dndbeyond website)
>https://cdn.discordapp.com/attachments/815028804103307354/988848856575934464/Filter_Undead.mp4
This should fix the above at least temporarily until we decide if we are going to build it ourselves. It delays the height change by 0.1s which seems to give it enough time to select the object.
The bug was happening most often with the items at the bottom of the dropdown.
> Fix drop down selection issue

- MessageBroker.js
- Token.js
Fixes #469 
Performance on the `Token#drag` method is mediocre, since the token is still moved to the maximum allowed position with each fired event.
I fear that stuff may break if we return out of the `Token#drag` method when we are outside of the scene.
For configuration, I added `Token#SCENE_MOVE_GRID_PADDING_MULTIPLIER` which defines how many grid fields a token can be moved outside of the scene.
> Constrain tokens to map #469

- ScenesHandler.js
As reported in Discord, some books aren't loading properly. It looks like DDB finally got around to updating those books to match some of the newer ones. 
I also found that we fail to find some images. Here is an issue for that work https://github.com/cyruzzo/AboveVTT/issues/584
> fix some sources fail to load chapter listing in scene configuration

- ScenesPanel.js
it was probably just a typo since it was setting the root of the new folder with itself as a parent 
fixes #594
> fix issue creating new folders at the root

- Token.js
Another missed part of #591 
This doesn't fix the ruler. 
I also ran into another issue where long line AoEs rotated still gets stopped by the token bounds as if it wasn't rotated. It may be worth and easy fix of just rotating the whole token for line aoes instead of the token-image since it likely won't have health, conditions etc as an AoE. Assuming that fixes this - not sure it would the bounds that contain the tokens might be based off something else.
> Fix selection box rotation

- Token.js
Since this addition is handled in the lines (1562 & 1563) above adding it twice made snap to grid token drag off and it feels weird. This doesn't fix the problem I've noticed with dragging a token that scrolls the window - that still puts the token off the mouse a bit. 
This partially fixes #605 for one of the dragging issues.
Edit: Doing more testing this looks like this also fixes non snap to grid token dragging a bit. On main it snaps to the corner of the token with this it stays where you grab it.
> Fix snap to grid over calculation

- Main.js
- MessageBroker.js
Better place to request syncmeup for loading both initial and into new scenes for players. I think this stops the race condition that was a problem before.
Credit to @Rishabh2 for working through this to find the issue
Edit: Also move the journal sync here as it was erroring out the same
> Fix loading combat tracker on initial load and scene swaps for players

- SidebarPanel.js
- SoundPad.js
This builds the sound panel for the players so the DM can control it. It seems it wasn't being built for players at all and sounds couldn't be played.
May also work better with #613 due to some syncing issues. 
Credit to @pensan for digging through this as well
> Fix: Build hidden sidebar for players so sound can be played properly

- MonsterDice.js
Gives a type error on setting the `const` to null below. Changed to `let`
Fixes #623
> Fix extras tab player rolls

- Token.js
Example:
https://user-images.githubusercontent.com/65363489/180084059-b3732766-37c6-44cf-8131-b6f1a7dcb5bd.mp4
Another token dragging issue that might help Fix #605
> Fix: Token should remain on cursor when dragging a token and scrolling the map or zooming

- TokensPanel.js
This allows the custom sizes when clicking the cog on players or monsters to properly save and work. Defaults to the current sizes when one is not set manually.
Fixes #626
> Fix customization for monsters and player sizes

- built-in-tokens.js
Item id's are set using the folder path and name but sanatize them removing special characters and replacing them with _
This caused ! and ? to have the same ID. I've set a name with normal characters for now but prehaps we should look at allowing special characters as names but I feel this would only apply to this type of token as others would have other characters too.
> Fix provided token ? showing up as !

- ScenesPanel.js
The server adds some FogData when the `update_scene` event is fired on the server and `isnewscene` is set.
```
if(recvMessage.data.isnewscene){
delete recvMessage.data.isnewscene;
promises.push(ddb.put({ // also initialize fog data
TableName: process.env.TABLE_NAME,
Item: {
campaignId: campaignId,
objectId: "scenes#"+recvMessage.data.id+"#fogdata",
data: [[0, 0, 0, 0, 2, 0]],
}
}).promise());
}
```
Currently, the `ScenesHandler.persist_scene` function is always called with `isnew = true` in the ScenesPaneljs.
This will lead to scene updates are always treated as 'new' which causes the server to add the reveal.
When later the `custom/myVTT/fetchscene` is fired, the data send by the server will always include the 'reveal all' data.
This PR will set the `isnew` flag to be always false when …
> Fix fog get resetted after editing a scene  #597

- Fog.js
- Token.js
- abovevtt.css
Here's an option for fixing the aoe selection of lines. This changes token selection target to the images which are also already the drag handles for tokens. It made sense to me to have the drag and selection targets the same and it fixes this issue and allows selection of some other scaled tokens that might not be square. Might want to do some testing to see how it feels for you guys.
This also hides the invisible parts of the line aoe token so they don't stop you from interacting with the rest of the map around it.
> Fix token selection for aoe - changes the selection target to the image

- Token.js
Tracked it down to a copy paste error where it was comparing the ```token.options.left``` with ```token.walkableArea.bottom```.
I also added the 1 size padding we allow for moving with the mouse already.
Fixes #624
> Fix moving with arrow keys towards the right side of some maps

- CombatTracker.js
- Token.js
The current logic only checks the hidden-name token option for monster tokens. This PR extends that check to all non-player tokens.
> Only player token names should always be visible

- ScenesPanel.js
On validation of maps urls this will check if it is a data: url and replace it with a warning about data: urls. A. Buttons are default type='submit' when in forms so I added type='button' to prevent it from bypassing the validation if enter is pressed.
Closes #631
> Fix: add 'data:' url check for maps and remove it.

- Settings.js
The setting description for border and health aura are backwards and non-conforming to other settings. I've changed them to conform and correctly describe the current state.
> Fix hover setting description for border and health aura

- abovevtt.css
An enhancement to dndbeyonds tooltips. This allows them to scroll - see example video: 
https://user-images.githubusercontent.com/65363489/184273469-7bc36287-a57b-4c9b-9861-d7bf280bd92a.mp4
> Allow tooltips to scroll

- Journal.js
Reported by Nikki on discord: https://discord.com/channels/815028457851191326/815028457851191329/1007692971644297306
The scrollbars are not showing up until resizing the journal window for players. This is due to height auto not playing well with overflow contents for whatever reason. This overrides the height in player view setting an initial height other than auto.
> Fix player view journal initial scrollbars

- Token.js
- TokenMenu.js
Tried to add scaling limits (#258).
Used `25px` as min size, and `1000px` as max size in the Token class. Please change the values if you find other values more appropriate.
Also added a clamp to the `Token Image Scale` slider that matches the HTML form input values.
> Add limits for token size #258

- TokenMenu.js
This should fix the token size bug when multiple token are selected. It should also now show `multiple values` correctly when multiple size values are present instead of always showing custom.
> Fix multi selected token size changes

- CombatTracker.js
The DM button is not highlighted on initial load. This is due to not creating a new Token() and instead sending a false token back when it's not on the map. This causes an error when we try and call functions from the token class.
This fixes that error and allows the rest of the function to load - which allows the scene button to be highlighted properly and other behavior returns to normal
> Fix - DM scene button on initial load

- abovevtt.css
Combat tracker in player view cuts of 3 digit+ health.
This allows for larger numbers without having to resize the tracker 'window' larger
> Fix combat tracker hp width for player view

- Settings.js
This fixes an error when clicking the configuration menu. When it creates the example token it was also sending the delete message to players. This caused an error for trying to delete a non-existent token.
> Fix sending delete message for configurations "example token"

- Fog.js
Occasionally I'm getting an error loop since it never gets to `cancelFadeout()` below since it errors at `clearRect`. This causes the `setInterval` to keep going forever. I'm unsure if this is weirdness with clicking to fast or out of the canvas or some race condition but this prevents the behaviour.
I can't reliably reproduce it unless I manually set the ctx to undefined. So I'm not sure of the cause. Edit: Clicking the canvas breaks the loop as `drawing_mousedown` triggers `cancelFadeout`. So not as bad but still an annoyance.
This was causing performance issues for about ~30 secs and sometimes it would remain unresponsive.
> Fix occasional error loop

- Token.js
- TokensPanel.js
Currently Token drop in center of view places token somewhat off to the side as it wasn't taking into account the size of the token. When zoomed out or using larger AoE's this problem appears worse. This should fix that. This also takes into account if your side bar is open and centers it on the playable area that is visable. 
See example video:
https://youtu.be/raLP3ALdV0w
> Fix center of view drop for AoE and tokens

- SidebarPanel.js
- TokenCustomization.js
I worked through this bug with @IanPK on Discord. If you name a custom token with a number, it gets parsed as a number instead of a string. Down the line, it breaks trying to parse a string on a number. This fixes both places.
> fix: token customizations with numbers for names break the tokens panel

- Main.js
Reported by: invictus92 in discord
https://discord.com/channels/815028457851191326/815028804103307354/1011273608510849155
This moves the roll context menu to the monster popouts.
> Fix - Move Context menu to monster popout instead of main window

- Journal.js
- Main.js
- abovevtt.css
This allows for popout notes. Useful for DM's if they have an map/adventure plan in the journal. The popout button is only available when displaying/viewing a note not editing it. Due to the editing requiring the iframe this may not be so simple or possible to popout when editing - similar to the gamelog requiring more from dndbeyond.
One of the functions used in this is copied over from #644. It will cause conflict but is the same function.
Another part of #630 
Example Video:
https://user-images.githubusercontent.com/65363489/186228725-4b7ab79a-196b-4afb-99a1-ee1dd4665272.mp4
> Popout Notes

- Token.js
Allows players to move their own token as per the description but disallows others from moving it.
> Fix: restrict player movement to match description - players can move their own token even if restricted just not other players

- Settings.js
- Token.js
Instead of storing the token measurement setting in `window.ALLOWTOKENMEASURING` (which doesn't get persisted anywhere), this treats it as an experimental setting which naturally gets stored in localStorage. The result is that the setting will persist across sessions so users won't have to re-enable it every time.
> store token measurement setting value

- abovevtt.css
This fixes some text that comes out white (from underdark mode sheets), the overly large pencil (edit) icon and the smaller concentration and ritual tags.
> fix some `send to gamelog` text especially sent from underdark mode sheets

- Main.js
We remove the player sheet's menu's in the iframe. This leaves the background position too low across various @media sizes. This should fix that
Example Video:
https://www.youtube.com/watch?v=FwA6Oh6GoO0
> Fix player sheet background positioning from removed menus in DM view

- MonsterStatBlock.js
Just noticed this tonight while playing with a gloomstalker and skeletons in combat that vulnerabilities are missing. This should fix that. 
Do we also want to consider hiding skills and saving throws when there aren't any to match dndbeyonds format?
> Fix - add missing monster vulnerabilities

- abovevtt.css
Pointed out by Addison on discord
https://discord.com/channels/815028457851191326/852495991227809802/1017914465183866940
In firefox we can't access the volume slider due to it not showing up if the width of the audio element isn't large enough.
This is just a quick fix until we get the audio rework in.
> Fix - Allow firefox to change volume by increasing audio element width

- CombatTracker.js
Hitting reset wasn't removing the current option from the token whose turn it was. Leaving 2 lines highlighted as current turn or having it the wrong turn on refresh.
> Fix reset button so that there isn't ever 2 lines highlighted as the current turn

- CombatTracker.js
As natemoonlife pointed out currently the beta doesn't load in local storage from the CT. This could be frustrating for users who ended mid combat.
This will load in the local storage people currently have on the first load. Next version I think we can delete the local storage but this allows people to go back to 0.79 and keep their local CT if there is a problem with the beta. Can always change this to delete the local storage instead if you would prefer.
> Load in the Combat Tracker local storage on first load of 0.80 and save it to tokens/cloud

- MessageBroker.js
Without this, token sizes are all messed up due to `size` being set to `NaN`
> protect against undefined gridSquares when downloading scenes

- CombatTracker.js
- abovevtt.css
This adds names to the combat tracker as seen #704. Requested by Garret is discord and myself as I find I hover over the CT a lot for names.
https://user-images.githubusercontent.com/65363489/197122912-dd9487f1-9437-4a1f-8f26-8ca2859490a0.mp4
Pretty much had done the work when making a mock up so just throwing up a PR with it. Not much time lost if we decide not to go with it.
This closes #704.
> Add names to combat tracker - players will only see visible names outside PCs

- Token.js
- abovevtt.css
I'd like to soften the hp bars a bit and have them styled a little more like other elements we make. 
I find it helps with visibility (at least for me) slightly and it fits a little better. I kept it roughly the same color just a tad lighter for visibility/reduction in harshness. Slight font size adjustments and remove half pixel positioning that causes some visual glitchyness/blurryness.
____
Edit: Added scale with zoom based on token size example:
https://youtu.be/B_70Z2WOkKw
Made a tutorial video for if this gets approved - better to have and not need. https://youtube.com/watch?v=hW94rT3eOtU
Examples new on left - old on right using the same zoom levels:
> QoL - HP token inputs visual adjustment (minor visual changes for visibility and scale on hover/focus based on zoom)

- ScenesHandler.js
- ScenesPanel.js
- abovevtt.css
This should fix missing subchapter maps. This makes sense for me because often these subchapters are meant to be run separately - see icewind dale. 
Edit: I went through a bunch of the books and had to make some more fixes as there is quite a few combinations but I think I've caught most/all of them now. 
Eg. missing sub chapters
Live vs Fix for import positioning:
vs
Maps glossary Maps:
> Fix - missing subchapter maps, 'Maps / Poster Maps' maps, Appendices maps/handouts and Fix import button layout

- ScenesPanel.js
Related to #717 - it's hard to fix maps that are scaled.
When a map is scaled and you load into the super mega wizard it doesn't set the scale until after the map loads. This causes the grid to be the wrong size when you click good enough.
This fix moves the scale change to before the scene load call.
> Fix - super mega wizard when map is already scaled

- Main.js
Reported in discord by St3pm
Everytime a resize was rebuilding the sidepanel, events were getting duplicated. It also was clicking extra buttons (defenses). This fixes both issues.
> Fix - conditions button Error 500 from too many event clicks

- Main.js
- abovevtt.css
Reported by Pedrus
https://discord.com/channels/815028457851191326/815028804103307354/1034611587954262026
Since dndbeyond now loads the builder on top of the character sheet it doesn't force a load somewhere else. It ends up with the builder behind the map and a bunch of the ui breaking.
This hides above stuff so the builder is viewable. Then adds the link info to the character sheet button in the builder to force a reload into abovevtt when it's clicked.
> Fix - PC go to builder button

- abovevtt.css
I've run into this a lot but also mentioned on reddit.
Lots of character art images are taller then they are wide. Currently the way the images fill the token is they zoom towards the center. This works great for wider tokens.
But a lot of character art is taller than wide and has the characters face near the top. 
This should be better in most all cases for `circle` or `square` styles token art that use taller images. It shouldn't effect wider images.
https://user-images.githubusercontent.com/65363489/198838262-2f3047ae-d250-4b2c-a4c3-b81655ccd345.mp4
> QoL - Vertical positioning of token images with a larger height then width.

- Main.js
Reported on discord by shannon
When player view is resize it doesn't start to monitor sidebar changes again. This fixes that and allows the gamelog button to show up again.
> Fix - `send to gamelog` button no longer appearing after resize of player view

- Main.js
- MessageBroker.js
Reported on Discord
On scene swap the map currently fades in. Since the darkness layer is white behind it it looks like a white flash. This should resolve that by hiding the darkness layer and showing it again when the map is loaded in.
> Fix - Beta on scene load white flash

- Token.js
- abovevtt.css
When a scene loads with a different scale. The hpbar font size doesn't update on tokens with how I had done it. Reverting back to using  `fs` variable and adjusting positioning to match centering.
To replicate put a player token on a map, then load a different map with a larger/smaller scale - occasionally the font-size won't update and it will be too small/large until the token is moved and then the hpbar interacted with.
> Fix - Beta hp inputs font size when scene loads with a different scale

- Fog.js
- TokenMenu.js
Reported by natemoonlife on discord - even with auras disabled and/or no darkness auraislight was taking effect.
This disables the check if darkness = 0 & auras are enabled. This also allows token sync to not be an issue between a scene fully light outside a cave vs with darkness within.
> Fix - Beta light only when darkness is set and auras are enabled

- CombatTracker.js
Sometimes initiative ends up out of order in the popup and every time a token is placed it pops to the top of scroll. This should fix it to be at the current turn.
> Fix - Combat Tracker initiative order on rolling groups and stop it from popping to the top of scroll

- ScenesPanel.js
- abovevtt.css
Reported on discord
Currently when the darkness filter is changed with a click the change can be jarring. This smooths it out.
https://user-images.githubusercontent.com/65363489/199291739-58dc1e45-cc42-480f-b183-4e57535c51b0.mp4
> Beta QoL - smooth transition on darkness when clicked instead of drag

- TokenMenu.js
I accidently removed a if statement continue that stops the hp roll drop down from showing up in the token context menu. After they are placed this setting isn't needed in the menu.
>  Beta Fix - remove accidently added context menu item hp roll

- abovevtt.css
Reported on discord 
https://discord.com/channels/815028457851191326/859099351711875092/1037805722974568509
This should stop it from wrapping at all zoom levels of the browser
> Beta Fix - Stop player card passives from wrapping when the browser is zoomed out

- Token.js
Added update_and_sync to move(top, left) - removed redundant code that would run twice otherwise. This fixes light revealing tokens with arrow key movement.
reported on discord: https://discord.com/channels/815028457851191326/859099351711875092/1037805722974568509
> Beta Fix - Check light auras when using arrow keys

- Jitsi.js
So I found another official jitsi implementation. 8x8 offers free video that uses jitsi and acts as a relay. 
Found the server here:
https://jitsi.github.io/handbook/docs/community/community-instances/
Now I don't know if they have the same thing going on where it will lock us out when more people are using it I couldn't find any explicit limit on searches but it's currently working for me.
If we find this server also has the same limit - unless there's another free server amongst the community servers I don't see us being able to fix this.
Maybe fixes #713
> Potential Fix - jitsi embed

- Fog.js
- Main.js
- MessageBroker.js
- ScenesPanel.js
- Text.js
- Token.js
- abovevtt.css
Changing how the map scales, using css transform, instead of making the actual image and canvas larger significantly improves performance. It seems the majority of the performance problem is in the canvas being too large - especially noticeable with measure while dragging on. Basically any drawing/clearing action performed on a really large canvas is really slow, this includes the measuring tool, fog, drawing, text. By making the canvas scaled instead it performs those functions much better.
~~A nice side effect of this is drawings, fog, all the canvas stuff will scale with the map if scale changes after doing it.~~ This isn't true anymore - in order to make it work between versions I had to eliminate this. 
Example: https://youtu.be/qCRbt4SiaxY  - this is from Rise of Tiamat, Well of …
> Significant performance increase on scaled maps 

- KeypressHandler.js
- ScenesPanel.js
This has ctrl/meta+a run `select()` if pressed when focusing an `input`. Also removes the auto select from scene rows other than urls so minor adjustments/highlighting can be done more easily.
> QoL - ctrl/meta+a will select all text in inputs. Disable auto select on scene rows other than urls so minor adjustments can be made more easily.

- CombatTracker.js
Reported by Garrett on discord https://discord.com/channels/815028457851191326/852495991227809802/1039699690557546597
This should clear those values properly on del/clear. 
Edit: This also looks like it was happening on scene swaps where it was updated for the session but not saved under certain circumstances. Added a fix for that as well.
> Fix - Clearing/updating current turn and round properly from tokens on del/clear/scene swap

- MessageBroker.js
Reported on discord
Problem example: https://www.youtube.com/watch?v=wCgIupTUSTE
Fix example: 
https://user-images.githubusercontent.com/65363489/200763546-cb741ebf-95f8-4916-8e62-2c5cd6e9d6ec.mp4
> Fix - When DM disables `auraislight` on a player token run check for visible tokens for that player

- MonsterStatBlock.js
- abovevtt.css
This adds classes from the character sheet version of monster stat blocks and makes a few edits in the css to match the styling.
Before
After
> Fix - monster statblock styling in player view doesn't match DDB style

- Token.js
Reported by natemoonlife on discord https://discord.com/channels/815028457851191326/815028804103307354/1041084687197687908
This changes the `token.options` copy function from `Object.assign`  to `$.extend(true,..`. This goes from a shallow copy where nested items still reference each other to a deep copy where they aren't. 
This should fix any nested options that are used like auras for copied tokens.
> Fix - Auras updating unexpectedly on copied tokens (nested variables in token options were still being pointed to each other)

- Main.js
This returns the double click function if not on the select tool for pings. I've found when drawing/fog polygons especially it pings frustratingly often. This should reduce messages and avoid unnesecarry pings.
> QoL - Disable ping when not on select tool (stop pings when drawing polygons and other drawings)

- Main.js
- MessageBroker.js
- SoundPad.js
Since the video tag had 'muted' as a property no audio would play for sources other than youtube.
This allows sources like Gdrive videos to have functioning audio and has the audio slider apply to them
> Fix video map volume for sources other than youtube

- TokensPanel.js
Flea pointed this out to me on discord
Just a typo in the token warning. loose -> lose
> Fix spelling typo in token warning

- abovevtt.css
Pointed out on discord by addroddyn. Context menu flyouts if the mouse is moved out of them when trying to type in an input it will hide the flyout. 
This sets focus-within to keep it visible when focusing an input.
> QoL - when inputs are focused keep context menu open

- Token.js
- abovevtt.css
Reported in discord as a bug by Harknail.
Large custom tokens like ships in spelljammer have their AC still increase in size but not the health bar.
Example image
https://cdn.discordapp.com/attachments/815028804103307354/1046901960143556628/image.png
This allows them to scale properly and I've chosen 10 units wide to be large enough to not scale the hp bar at all based on zoom as it's still large enough to view at furthest zoom in my opinion.
> QoL - Allow hp bars to be larger for custom size tokens.

- Journal.js
These buttons are available on dndbeyond's tinymce and I think they'd be quite useful to have.
Example:
> Add table and code button to Journal

- Main.js
- SidebarPanel.js
Gdrive gives multilinks a comma seperated this would allow quick addition of those links to tokens.
Example video:
https://discord.com/channels/815028457851191326/815028716040224818/1051686680551235604
> QoL - Allow token image split urls on `, ` (comma space). Allows mass add of gdrive images easily or other images with comma seperation.

- TokenCustomization.js
The new Dragonlance book includes the Kender race. This adds them to the DDB tokens that we provide even though DDB doesn't have any images for them yet. When they get around to adding images for Kender, they will just show up because we're now looking for them.
> Update DDB tokens to include the new Kender race

- abovevtt.css
since these are now in the container remove the selectors otherwise we don't see the whole map
> Beta Fix - Fix scaled map size/position: Remove map, darkness layer from scaled css selectors as the new container is already scaled

- Main.js
- abovevtt.css
As discussed with mikedave the map container should have the size set on map load. This is to make sure the container is as large as the map otherwise the map won't display as everything overflowing from the container is clipped/masked.
Since it was in the same area this should also fix the map fade in. I have set it to 1.5 seconds but it can be adjusted if we feel it's too long/short.
> Beta Fix - Maps should fade in to avoid flash bangs, map container size correctly set on load and stop transparent parts of maps from revealing auras

- Main.js
- MessageBroker.js
- abovevtt.css
So Nate turned me towards the simple solution here. Just make the image background black. Fixes the issues completely. Maps load without being masked due to CORS issue and we don't get white areas around transparent maps. 
Since certain image sources were giving errors on masks this is the best workaround. Also simpler/less processing than what I was doing before anyway. I removed the previous code I tried to fix it with since it's no longer necesarry.
Thanks to Nate for the assist.
I also reduced the darkness max for DMs again as dark maps were hard to see still. This should be a bit better - we can always adjust further based on feedback.
---
Firefox player left - chrome DM right
> Beta fix - white behind transparent maps for all browsers and bump up DM max darkness a bit so darker maps are still visible.

- Fog.js
On scaled maps the polygon final click box was too specific due to new scaling. This fixes it to be the correct 'hit box'.
> Beta Fix - Polygon box should behave as normal. Box was too specific on high scaled maps

- ChatObserver.js
- DiceRoller.js
- Main.js
- TokensPanel.js
- abovevtt.css
This does 2 things for PCs. First, it adds the ability for slash commands to parse stat modifiers for players. Second, it allows players to add slash commands to item customization notes which adds buttons to their sheet.
This allows slash commands to be more than just static numbers like `/r 1d20+5`. This allows the slash command to dynamically parse stat modifiers like `/r 1d20+DEX+PB`. 
This allows players to add custom dice roll commands as buttons to their character sheet. This is useful for things like the Savage Attacker Feat where you roll the damage dice twice and take the larger of the two rolls. To accomplish that, a player can type `/dmg 2d8kh1+DEX Savage Attack` into the chat box and hit enter. Instead of having to type that out every time, they can now add a button to the …
> Stat modifiers in dice rolls formula and custom dice roll buttons on items

- Main.js
This adds a backup popout game log cleanup in a timeout. Until I can dive into why it's not triggering the onload event sometimes this is a quick fix.
> Fix - game log popout wasn't loading sometimes.

- Fog.js
- abovevtt.css
Fix the text tool erase to erase the correct location.
After some feedback in discord I looked into quality of the scaling. Using the same scaling idea but the ctx function for scale rather than css increases quality again while retaining the performance boost from my testing.
> Beta Fix - Text erase will now erase in the correct location. Better canvas quality on scaled maps while retaining performance increase.

- Fog.js
- Main.js
- MessageBroker.js
- ScenesHandler.js
- Text.js
- abovevtt.css
Changing text to SVG allows it to scale better with zoom giving it better quality.
We've had some canvas performance issues, although text isn't changed often 1 less large canvas may help. Scaling text in canvas doesn't look great.
This starts off by allowing the DM to move the text if they have the text tool selected. It works off the same data so it does pull in old text and convert. If your players are on the old version new text will still draw as canvas drawings. 
It does add a few extra data points (id, backround fill) as we no longer need to fill the background rect seperate and a way to identify them was needed.
This will also allow us to potentially edit the text ~~in the future~~ now. 
https://user-images.githubusercontent.com/65363489/217996328-8b076056-fd70-4033-93b4-83fffa413f …
> Editable, Moveable, adjusts with scale changes to stay in postion and better quality text

- ScenesPanel.js
- abovevtt.css
Currently the options beside show grid get hidden when the button is clicked disabling it. However they aren't hidden if it starts as disabled. Also the new things I added weren't being hidden (didn't realize these things got hidden tbh but it makes sense). 
old:
fix:
> Fix - always/properly hide grid display options beside show grid

- Fog.js
We should make a 83.1 this is pretty game breaking. Fog will hide tokens when they shouldn't be hidden and visa versa. 
I missed taking this out when I changed the scaling type to ctx.scale() for fog.
> Fix - Fog not calculating if token is inside it correctly

- abovevtt.css
Darn I was too slow to update the PR before merge lol.
This just adds a blur to the backdrop - looks nicer on some maps where it was too transparent. Also condenses the css instead of repeating it.
Examples:
If you merge this no need to include it in the change log separate from the pause.
> Adjust background of pause - add backdrop blur and condense repeated css

- MessageBroker.js
- ScenesHandler.js
- TokensPanel.js
closes #617 
This was due to our `cached_monster_items` being cleared when we change scenes. This was originally cleared to try and keep our memory footprint low, but the size of this object rarely grows larger than a couple dozen items. Plus, keeping these items around in cache means that we don't have to refetch these items from the DDB API so our network traffic will be reduced if we keep this cache around.
> stop clearing cached_monster_items on scene load

- Fog.js
I don't think it's necessary to push this to live right away can go in beta. Noticed it while trying to fix the other more important issues.
Just currently light is hidden always when in fog. This allows the option to work correctly again. For when you want people to see auras/light coming out of fog but not the token. Like light sources (enemy carrying a torch) coming from around a corner.
> Fix - Hide aura in fog option

- PeerCommunication.js
- PeerManager.js
The problem here was the way that I was using the debounce functions for fading them out. The way that a debounce function works is by calling `setTimeout`, storing the id of the timeout, and clearing/resetting it every time it's called. So any time the timeout gets cleared, it essentially delays the execution of the function. I was calling the same debounce function with different playerId variables which ended up clearing the previous execution which may or may not have been called with a different playerId. Since the timeout id is unique to function, but not unique to the parameters it's called with, fading a playerId would clear out the execution of other playerId fade outs. 
The solution is to store a debounce function for each playerId. An alternative could be to track timestamps …
> Fix: peer cursors and rulers were not being cleared all the time

- abovevtt.css
A hard to trigger bug with light auras reported on discord. 
At some zoom levels the animation was causing flashing. I had to manually set my zoom and move it bit by bit till I found one. Musashi and F I Z Z C A N N O N both had this happen.  F I Z Z C A N N O N couldn't get it to trigger again once zooming away.
I've changed the animation at the zoom level that was triggering it and the flickering stopped. I then couldn't reproduce the flickering so I'm hoping this caught it all.
> Fix - Flicker on certain zoom levels when using light auras

- Fog.js
- Token.js
Some minor bug fixes, missing &, missing != undefined. 
This prevents light from showing through walls. It also makes `reveal light to players` only reveal when in LoS of the players. Owned tokens will still always show light.
Examples for reveal light to players. Torchs in a room that you don't want them to see until they see the room.
Examples for owned tokens. A pet that they always want to see their vision.
I've added a radius for the ray casting - although not used just yet.
> Beta Fix - Minor bug fixes. Light improvements, revealed light only show when in LoS, owned tokens will still always show. 

- CharactersPage.js
This was due to re-using `above-vtt-visited` as a marker class. The aoe buttons use that, and I was doing the same with the dice buttons. Now I'm using `above-vtt-dice-visited` instead.
I also changed my multi-command parsing to use an array so I can check the length and return early instead of unnecessarily processing every note.
> Fix: player sheet aoe buttons aren't being displayed

- Fog.js
I thought I had done this already - oops. This should fix it
> Beta Fix - Stop walls from being erased when drawings are cleared

- Token.js
Only adds the group rotation grabber when more than 1 token is selected.
I don't quite see what mikedave in discord is seeing but I adjusted the grabber slightly to center the svg. 
I'll double check firefox in case that's where you saw the odd icon size.
> Beta Fix - Only have group rotation grabber when more than 1 token is selected.

- Fog.js
Also currently 'reveal light to players' tokens are checking vision when selected but players don't have access to their vision so it blacks out everything. This stops the vision check when those are selected properly.
Currently visible light sources aren't revealed until their token is but often the torch will be out of view but I'll want to see the light. (will only reveal on drop once merged with other pr - but a light source might still be around a corner or through some bars etc)
Example:
https://user-images.githubusercontent.com/65363489/220816887-326fc059-0b73-4093-8efd-72cf8928f362.mp4
> Beta Fix - See visible light sources coming around corners, and only check owned token vision when selected as as player.

- Fog.js
Currently if a DM checks a token for vision 'reveal' light sources are not visible. This fixes that.
Example
https://user-images.githubusercontent.com/65363489/220820619-0a4275c7-0720-4dcc-bca0-6b61d1da476f.mp4
> Beta Fix - DM see light revealed to players when checking player token vision

- abovevtt.css
The animation with a bunch of light on the map is not appreciated by the browser. Almost ironic the animation name was flicker lol
A static blur seems to resolve this issue on my end. Probably also will increase performance a bit. The animation was so subtle it barely had an effect anyway. 
https://user-images.githubusercontent.com/65363489/221227275-d4b399fe-e878-4651-909c-cf65c1b9d029.mp4
> Beta Fix - Prevent flickering when zooming due to rendering issues

- Fog.js
- PeerCommunication.js
- Token.js
Removes light_redraws that were getting called redundantly. Every token drag was causing 3 redraws when we only want it to redraw when it's moving animation is complete.
Also fixes an error where when the dragged token was cloned for peer streaming it was being picked up as a selected token to check vision for. Removing the tokenselected class from the cloned token fixes this error.
> Fix drawing light when a token is selected that someone else is dragging. Remove unnecessary light redraws.

- Fog.js
You can look at window.lightPolygon to see the difference but what this does is as it's checking closest points it only adds them if it's the first or last point on the closest wall. Since all the walls are lines it's unnesecarry to add every point along the wall. 
On average were looking at 360+ (1 for every degree rotation) down to in the low double digits on polygon points for the light polygon that is drawn on light redraws. I think this will give an improvement to performance for some people and it requires less data points.
> Beta Improvement - Only grab 2 light polygon points from each closest wall

- Fog.js
Currently vision doesn't update immediately after finalizing a wall or erasing one in the DM view. Player view works fine. This should fix DM view by adding redraw_light to the eraser and wall mouseup. If using segmented walls it won't trigger until the wall is finalized.
> Beta Fix - Update vision after finalizing a wall or erasing a wall for DM view

- Fog.js
- MessageBroker.js
- Token.js
I don't know what I was originally setting this up to do. I think I was trying to get the angles to each wall end point but that's unnecessary.  But there's no need to loop through all the walls. 
I've also increased the divisor which reduces the rays when checking for light to further reduce loops. This is an effort to improve performance on large maps and maps with many walls.
EDIT: I WAS MAKING THE SAME PARTICLE AND GOING THROUGH THE SAME GIANT LOOP EVERY DRAW. 🤦‍♂️😔
At least I caught it before release. This should be a huge performance increase on maps with many walls.
> Beta - Far fewer loops and rays when looking at light

- CharactersPage.js
- ChatObserver.js
- CoreFunctions.js
- DDBApi.js
- DiceRoller.js
- MessageBroker.js
ostrichwrangler on Discord helped me track this down. They had a character that wasn't showing up in the tokens sidebar. The root cause of it was the DDB API endpoint that I was using to fetch window.pcs didn't include the character. We were able to find a different (probably newer) endpoint that did. Changing to this endpoint fixes the problem, but it also gives us way more information. I updated DiceRoller to use the abilities in window.pcs if it exists, and I think we can clean up a lot of `DDBCharacterData` now, too. I'm going to start doing that in a different PR, though, because that will be a larger change.
Side Note: If you edit a character, the old DDB API endpoint will start sending the updated character data. I've seen this happen in other places as well. That hopefully won't …
> fix older characters are missing from window.pcs

- MessageBroker.js
I'm not sure what I was thinking when I originally made this timeout waiting for walls - but it was messing with fog. Some maps would load with full fog until the map was interacted with which would create the walls. Certainly don't know why I put fog in there with it.
Also some walls persisted between scenes due to it not being below the window.drawings check/reset - maybe I put in the timeout for this reason 🤷 but this should fix both issues.
> Fix - Some maps (Video especially) loading fully fogged until interacted with, walls staying between scenes.

- CharactersPage.js
- MessageBroker.js
- Token.js
Using @vlaminck's idea - This adds checks to our character sheet observer for hp, max hp, ac and conditions. If changed while in game it should force an update. It seems the reason updates aren't happening consistently is we aren't always receiving a character updated message from ddb. I send our own message and limit individual character updates to once every 4 seconds so we don't spam ddb with character data requests.
The DM and other tabs still rely on the current method of updating player hp but it's a step to making it better imo.
Example
https://www.youtube.com/watch?v=BxWLnbOv5vQ
> QoL - Force update player hp, max hp, ac and conditions shortly after changes when changed by a player using the in game sheet

- Main.js
- abovevtt.css
Due to my absence the patrons list has not been updated for months.
I've built on the backend a lambda that build a patron.json file and store it in our abovevtt-assets S3 bucket, then connected it to the Patreon api to update it automatically.
This PR remove the old l1,l2,l3 patrons list and change it to so that the list is dynamically loaded.  Patrons are now ordered by amount "donated" and marked with the different tiers (or extra pledges etce tc).
The splash screen is still ugly.
In the future we can use this same "dynamic approach" to change other pieces of the splash screen dynamically (like having a way to warn users of issues).
The splash screen is still ugly as it was.
> Change splash screen to dynamically load patrons list

- Fog.js
- Text.js
Putting text, drawings or walls on the map then after changing scale causing redraws (eg text hide on right click) would cause it to jump as if it was being scaled again. This is due to changing values in the window.DRAWINGS but not the scale. In this I replaced the window.DRAWINGS pointers with clones and make a few other necesarry adjustments to prevent this from happening. 
I don't think it's terribly common so it can wait until next beta.
> Fix - Text and drawings/walls sometimes jumping after map scale changes

- Fog.js
I went to ctx scaling when it was pointed out text was unreadable and it felt like the performance was still there. I was wrong abou the performance. I noticed this when I went to test stuff out in one of my test games that had an old map of nates that was insanely slow. Since text is no longer on a canvas I've adjusted all canvas' that used the ctxScale funtion to now scale with css.
This also has the side benefit of being able to go to larger scale sizes as we don't cap out on canvas size.
Example - first load is current. 2nd load is with css scaling. (Edit: fixed the grid size/offset after this gif)
https://imgur.com/Q8ClJkE
> Performance boost for scaled maps - Swap to css scaling again for canvas now that text isn't on the canvas

- CoreFunctions.js
I was only looking at open bugs before. Since they get closed when we merge PRs, we should also look at closed bugs.
> fetch all bugs from github

- Token.js
Remove the inline opacity on token deselect so token vision checking is cleared.
> Fix - raycast inline opacity removal on token deselect.

- MessageBroker.js
- ScenesPanel.js
- Token.js
- TokensPanel.js
So adjusting it from empty to remove seems to stop the folder structure and buttons in the scene panel from being retained in memory on scene swap. I _think_ based on what I've read this is because remove also gets rid of jquery event listeners. I was seeing some tokens and their conditions after so I made some adjustments there too changing the listeners to jquery ones. This seems to have gotten rid of those as well as remove was being used on them already. 
I tried the same for the token side panel but it still seems to be retaining some of that like the players. So there might be other things retaining it then jquery listeners. 
More info and screenshots in this discord thread https://discord.com/channels/815028457851191326/1091516699217506365
> Prevent scene folder structure/buttons from retaining on scene swap.

- Fog.js
- ScenesPanel.js
- Settings.js
- Token.js
- TokenMenu.js
adds a quick and simple option to default token options in settings. This option doesn't appear in the token context menu for now. I'm not sure this is how we'd like it to work in the end but this should entirely disable the feature when on for new token drops. It disables the light context menu in general on tokens drop with this setting on.
> Add disable token vision/light as a scene option.

- CombatTracker.js
- MessageBroker.js
Requested in discord by Musashi to be able to end turn of companions/pets. This allows players to end turn on player owned tokens.
Let's put this in the next beta after this release if we like the option.
> Allow players to end turn of `player accessible stats` tokens

- Token.js
When dragging a token across multiple moves sometimes it will look like it pauses and jumps when you pick it up quickly and continue movement.
This is a small QoL - when finishing a token drag wait 500ms before running light checks. Return light checks if the token is dragging after those 500ms. 
If anyone thinks another time would feel better for a balance in token drag vs light checking on the final drop let me know. I felt this was an ok balance between the light check being run at the end drop vs how long I have to pick it up to keep the drag smooth.
> QoL - Smoother token movement when dropped and regrabbed in a short time to continue movement.

- audio/mixer.js
I missed that google drive links weren't being parsed to get the correct audio src. This should fix that.
> Fix - Google drive/Dropbox links in audio weren't getting the correct audio source.

- MessageBroker.js
Reported in discord by Gawly and DM-Seraphim.
Since we pull data from all_token_objects to look at tokens not on the scene, we need to update those options when we receive initiative messages as well. 
I'm not sure why this works sometimes and not others - but this resolves the issue.
> Fix - initiative sometimes not updating to the correct number for players

- Token.js
Reported in discord locked tokens currently block click events for players. This should resolve that.
> Fix - clicks shoud go through locked tokens for players

- Fog.js
Reported in discord full brightness maps are darkened until a token is placed on the map. Even with no walls.
This was due to the shadow/line of sight layer being visible even when no walls are placed. No tokens = no line of sight, made a slightly dark map even without walls. This ensures there are more walls then just the border of the map before creating LoS shadows.
> Fix - Only show shadow/line of sight layer when walls are on darkness 0 maps

- CombatTracker.js
- Main.js
- MessageBroker.js
- audio/mixer.js
- audio/ui.js
This makes sure a default volume is set if the player joins without a DM and sends the YT volume from the mixer when a player connects.
Also beta fixes a bug I introduced in beta erroring on checking a token in ct_load. should have been data.current. 
When skipping ahead in a track don't try and set current time if we haven't loaded the audio yet / don't have a duration. Other wise duration = NaN and it errors out.
> Fix - Animated map audio, make sure a default volume is set so the DM doesn't have to change volume to get audio to play for players.

- Fog.js
Check token vision wasn't fully opaque on 0 darkness maps due to the new layering.
Another place height and width were backwards when setting the maps edge walls. This was creating a diagnol shadow effect as the wall didn't extend to the corner fully.
> Fix - Another bug with height/width swap causing a diagnol shadow to appear on tall maps, and check token vision should be fully opaque.

- Fog.js
I believe this should Fix #1117
> Fix - Scaled scenes token movement with arrow keys, should no longer run into invisible walls or get caught unable to move.

- abovevtt.css
The map scale was compounding the blur due to scaling - causing light near walls to blur too far past them. This compensates for that.
> Fix - Adjust light blur based on scene scale, this was revealing too much past walls on high scale maps.

- built-in-tokens.js
Have vision/light default to off on letter and number tokens. I think primarily these tokens don't have vision and it would be more common to use them as hidden tokens for the dm to mark things.
> QoL - default letter and number tokens to default have vision/light off

- CharactersPage.js
- CoreFunctions.js
- MessageBroker.js
- Startup.js
This does 2 things:
1. MessageBroker is now listening to the DDB `character-update` event again. It was removed by mistake in 0.90
* ~~I think this actually needs to be updated to fetch from the API because we expect the change to be included in the event which DDB doesn't send.~~ This has been done
2. `window.pcs` continues to update whenever we get any character-update event, but token updates are debounced. I did it this way because you can't pass variables into a debounced function.
* ~~As I write this, I realize, I need to clear `window.PC_TOKENS_NEEDING_UPDATES` after updating the token~~ this has been done
> Fix - some player data sync issues, debounce token updates in update_pc_with_data

- Token.js
While trying to replicate/figure out what was happening in #1122 I noticed that the debounce for redraw light would run before holding a movement key down triggered the next function call. 
For my setup 500ms captures the next call when holding down the key. I think this resolves some of the issue seen in the above PR as it won't stutter before letting go of the key for scenes with lots of walls or lower end pcs.
I'm going to hold off on this and the other improvements by Josh-Archer until next release since we're so close.
> QoL - Adjust redraw light delay to capture holding an arrow key to move.

- Settings.js
This should fix the import error. This was happening due to not setting true on writing to the mixer on import here. This is usually false when adding/adjusting tracks in the mixer. It needs to be true when switching playlists and in this case importing audio - to prevent the current playlist from updating before switching or attempting to update a playlist that may not exist in this case and causing an error.
> Fix - Import should no longer error and appear to hang

- TokenMenu.js
Reported on discord that the quick roll wasn't setting hp correctly. It wasn't using the get/set hp functions of tokens and instead trying to set options we don't use anymore. It seemed to work if I go step by step until the place() is called then it reverts to the wrong values. This resolves that. I took a look to make sure we caught this elsewhere and it looks like it's been updated everywhere else I could think to check / ctrl+f could find.
> Fix - quick roll hp changes, use token set/get functions

- Token.js
We have got at least one person reporting this error message with the token x,y being NaN. I've added some more variables to the error to see where it might be picking that up from. 
I also moved the canvas/ctx variable declaration out of the drag function so we don't have to grab those every event call. I removed some code we no longer use from start as well.
> Internal - Error update to help find the flying NW token bug. Move Canvas and CTX out of drag - lets not grab it every call.

- audio/mixer.js
- audio/ui.js
This fixes a bug with the loop button that would cause mixer tracks to pause when they shouldn't. Possibly also messing up loop. It was looking at a channel variable from outside the click function which has the wrong data - it should be pulling looking at the current state on click.
This also fixes and player side error that wasn't really having any effect since players didn't need the info. Just window.DM
> Fix - The audio loop button was causing the tracks to have the wrong pause setting

- MessageBroker.js
I wasn't sure if we wanted to call `showError` for any of these because it could be a lot. For now I'm just logging the errors.
This relates to #357 which I hadn't seen in a long time, but was recently found again in Discord.
I'm unable to reproduce what the discord user is seeing, but rolling from the Bigby's Living Hand stat block will cause errors that this will log out. There's probably a real fix for that stat block, but this PR is just trying to not break the MessageBroker websocket.
> better error handling and logging of MessageBroker events

- audio/mixer.js
There's a report in discord about audio playing a short bit then stopping. I think what's happening is the file is 'ready to play' but not fully loaded so there are interruptions. This makes sure the file is fully loaded before playing.
> Fix - Only play audio when fully loaded

- ScenesPanel.js
- abovevtt.css
By manually setting the grid size 50 this ensures we don't run into issues with exports that have large grid squares. For example if a UVTT file had 200px as the grid and a 40x50 grid we'd get a 8000x10000px map image - which often causes performance issues due to large canvas'.  With 50px grid we cut that down to 2000x2500px - still a good size to play on but reduces performance issues. 
I added a comment about future changes we can make to improve even larger maps as well taking advantage of scaling.
This also includes some fixes for light in the imports.
> Beta Fix - Improve large UVTT map performance and fix light color/range

- Token.js
- abovevtt.css
Fixes #1193
This removes tiny token ac pointer events and scales them the same on all maps regardless of grid size.
> Fix - Tiny token AC blocking movement

- audio/mixer.js
Relying on play to load each audio track doesn't seem to load all tracks after awhile. This seems to work better.
> Beta Fix - load() audio if it isn't already loaded (load events relying on play only don't seem to work as well)

- ScenesHandler.js
This should fix the grid wizard aligners and have them show up again. Had to add the UVTT variable to the scene load.
> Beta Fix - Grid wizard aligners and controls should show again

- Fog.js
light drawings if you had 0,0,255 would register as no light/black light and hide tokens. This resolves that.
> Beta Fix - Drawn light should check for full black so that colors like blue with 0 red work

- Token.js
This should fix one of the token movement errors. 
For some reason walkablearea.right and walkablearea.bottom is null sometimes. This should reset those values if that happens when the token starts moving. My guess is one of the window variables in `preparewalkablearea` isn't initialized when loading into a scene sometimes causing some tokens to have this issue.
> Fix - one of the token errors where it jumps to the NW

- Fog.js
Adjusted the bucket fill to the appropriate location when on a scaled map
> Beta Fix - bucket fill drawings/light when on a scaled map

- audio/mixer.js
Current when the master volume slider is changed on the player end it jumps back to the last state position. 
This should prevent that by not running the syncPlayers (mixer._players not player view). This is an extra step anyway when changing the volume that is unnesecarry.
> Fix - Changing volume as a player shouldn't reset track position

- audio/mixer.js
Audio load requests in the 'pending' state play after loading even if they were cleared from the mixer
This should resolve that and prevent them from playing if they were removed.
> Fix - Prevent audio from playing if it was loading when cleared from the mixer

- KeypressHandler.js
Got a couple reports of pasting sending the token to random spots/top right of map. 
I think this is due to pasting when the cursor is off the map or a bug with mac paste due to getBoundingClient not specifying what is being subtracted (it returns an object {x, y, top, bottom .... } ). This should resolve both cases.
> Fix - Only paste tokens at mouse if mouse is hovering the map

- Journal.js
Fixes #1258
So it seems sometimes dndbeyond has compendium instead of sources in the url. I'm not sure if this is due to purchasing just the compendium product vs full product or if they've made a change somehow. I'm not getting compendium in my urls but the url does direct to the book if I go their manually.
> Fix - when creating a scene from dndbeyond it should no longer throw an error when compendium is in the url.

- CharactersPage.js
- ChatObserver.js
- DiceContextMenu/DiceContextMenu.js
- MonsterDice.js
- Settings.js
- abovevtt.css
There has been a few request to have an option to not use ddb dice. This would be an option in experimental settings. Feel free to grab this and add to it/finish it up.
To Do:
This is currently using `window.AboveDice = true` in the console to enable this.
(this will be replaced by the option.)
Monster example:
https://cdn.discordapp.com/attachments/1118492516510072882/1118562776995074178/dice_example.gif
> Feat: Option to use rpg dice roller instead of ddb dice.

- DiceRoller.js
I was using roll.name instead of roll.action to get the roll title for the gamelog message.
> Beta Fix - use roll.action for the roll title

- DiceRoller.js
- Main.js
- MonsterDice.js
- abovevtt.css
When using non-ddb dice the dice under chat should no longer used ddb dice.
Open5e monsters some buttons weren't working with non-ddb dice. 
Hovering a roll in the gamelog for monsters wasn't showing the full dice results just the expression.
> Beta Fix - Non-ddb dice open5e monster rolls, dice buttons under chat, hover should always show full result

- MonsterStatBlock.js
- TokensPanel.js
A fix for ddb monster list not loading and stat blocks getting stuck.
This was happening due to undefined id's being requested from ddb's server.
> Fix - DDB monster list not loading and stat blocks getting stuck on one monster

- audio/mixer.js
- audio/ui.js
This moves onto the next channel if a src is undefined and removes it from the mixer.
> Fix - undefined audio channel src causing type error on `startsWith` when loading into abovevtt

- TokensPanel.js
This should resolve the image customization not showing up in the sidebar when added.
> Fix - Open5e properly display added custom images in the sidebar

- Main.js
I missed window.DM on the zoom part of the projector setting.
> Fix - projector mode zoom should only send from the DM window, should prevent odd behaviour when multiple pc views are open

- CharactersPage.js
- Token.js
- TokenCustomization.js
- TokensPanel.js
Currently some customizations on player tokens don't set properly and are overridden by the syncing of player tokens. This should resolve that issue - the custom border should also update to the theme when a player changes their theme.
> Fix - Player token customizations should properly override token settings.

- Main.js
- ScenesPanel.js
The projector button wasn't displaying if the setting was on when loading in. This fixes that.
Swapped the settings order in the light/vision settings so that darkness filter is right above the selectable previews - since they are linked.
> Beta fix - display projector button if already on when loading in, reverse setting order so it makes more sense in light settings

- Token.js
Instead of stopping the players from being added to the paste buffer when copied - only stop them from being pasted if they already exist on the scene.
> QoL - Allow copying and pasting player tokens onto scenes they don't already exist on

- Fog.js
- MessageBroker.js
6px that was carried over from drawings is too small for lighting anything. This sets light defaults to 1 grid width on scene load.
> Beta QoL - set light line width to 1 grid width by default on loading a scene.

- Main.js
- Token.js
This allows a player to set a condition using the context menu on their own token instead of whispering themselves. Also should fix the buttons so that it displays on the token as well as the sheet. I had to add a slight delay to allow our system to grab it before the info disappears.
> QoL/Fix -  auto set  standard conditions if a player selects it on their own token and request button should display condition on token again.

- TokenMenu.js
- abovevtt.css
I accidently left in a rtl for the buttons and this adds a game id for lock conditions
> Beta Fix - have locked coniditons per campaign, fix top right button order

- abovevtt.css
Makes the background none and removes pointer events on the main window but adds them to the content.
> Fix - remove sourcebook journal background so it can be minimized properly

- TokenCustomization.js
Should only update the customization with token size when it exists.
> Beta Fix - PC token customization should no longer cause errors on placing the token a 2nd time after adjustments

- ScenesPanel.js
Fix UVTT light transparency. I had the scale wrong thinking 0.8 was 80%. It looks like the scale runs from 0-4 or ~ along those lines.
> Fix - UVTT Light transparency

- SidebarPanel.js
- TokensPanel.js
- abovevtt.css
Adds the ability to hide/reveal player tokens and token folder in the token panel. Adds the hide/reveal to the context menu and a button to temporarily reveal hidden ones at the top of the token panel.
I've been wanting to be able to hide player tokens for awhile since I run multiple groups in 1 game - this way I can hide all the other groups for that game.
It was also requested to be able to hide unused folders - like open5e etc.
> QoL - ability to set unwanted player tokens or token folders as hidden.

- abovevtt.css
Reported on discord players context roll menu gets stuck open unless you complete the roll.
https://discord.com/channels/815028457851191326/815028457851191329/1133253659845726362
I think awhile back ddb changed this to cover the sheet and it stopped us from clicking on anything. Seems to no longer behave that way and this solves the issue.
> Fix - issue with roll context menu being stuck open unless rolled for players

- Main.js
This should resolve the issue with the new dropbox url architecture. 
> Dropbox is moving to a new link architecture which centralizes links on content rather than on users. We'll refer to these "/scl" links as "new links" and the previous "/s" architecture as "legacy links".  Part of the new link architecture is the addition of an rlkey parameter.  It is this parameter which grants access to the content.  That is why removing that parameter results in visitors having to sign in and request access. 
> 
> We’ve paused our rollout to better understand this issue.  Since the issue appears to be with how the new link format is interacting with 3rd party applications, we need to understand these use cases more deeply.
> Fix - issue with new dropbox urls for those that have had it rolled onto their account

- Main.js
- ScenesHandler.js
- ScenesPanel.js
Another fix for grid wizard in beta.
> Beta Fix - issue with scaled maps grid wizard and make sure subdivided squares are off in wizard

- CombatTracker.js
reported on discord - when trying to adjust multiple initiative numbers in a row it will deselect the initative input when reordered. If trying to delete the init with the delete key at the time this ends up causing selected tokens to be deleted. 
I've taken this particular reorder out of debounce so it happens immediately and the next input isn't deselected.
> Fix - Initiative boxes being deselected on reorder, occasionally causing tokens to be deleted accidentally when trying to erase the input

- ScenesPanel.js
This fixes an issue where we were persisting the scene then reloading the scene locally. This just sets the scene data for the scene then loads it locally since it's going to be saved via the grid wizard anyway.
> Fix - issue with grid wizard double persisting and loading the map - this sometimes caused UVTT maps to ghost overlay when clicking to quickly.

- CombatTracker.js
Currently reroll sets the current turn before the reorder has been completed. This should resolve that issue.
> Fix - issue with reroll not correctly setting the current turn to first in initiative.

- Journal.js
Fixes an issue I introduced in beta.
> Beta Fix - issue with tooltips causing custom statblocks not to load when copied from dndbeyond

- Journal.js
I wasn't able to find a json object or api I could grab this from so I load the spell page to find it.
> Beta Fix - fetch official spell ids for tooltips

- Main.js
This frees up some memory by only having 1 iframe that we change the src on when a bookmark tab is clicked. We also don't load the help doc until a tab is clicked.
Adds more tabs that are planned to be worked on - don't need a new release for these tabs that way.
> Beta - more help tabs, only use 1 iframe and only load once a tab is clicked

- Journal.js
Fixes issue with detection in custom statblocks when nbsp; is used in place of a space and add recharge rolls
> Beta - Add recharge rolls to custom stat block; Fix detection issue when nbsp; is used in place of a space.

- audio/ui.js
Many people have the issue finding this section of the ui confusing. I don't want to remove the ability to pause/play all tracks in a playlist. This retains that function without having to hit two buttons to start playing a single track.
> QoL - Audio play buttons (mixer and library) will now also toggle the global mixer play.

- audio/mixer.js
fix for new dropbox url format - I missed this when I fixed it for maps.
> Fix - dropbox new url format fix for audio (missed on last dropbox fix)

- Journal.js
When googledrive or dropbox images are added to a journal convert them as we do maps
> QoL - Googledrive and Dropbox images should now work in notes and statblocks

- Main.js
Minor spelling mistake in the chat roll commands examples. Theives -> Thieves.
> Spelling correction in chat roll example tooltip

- abovevtt.css
Just makes the ac bold for readability.
vs
> QoL - make token ac bold for readability

- CombatTracker.js
- StatHandler.js
Fixes an issue with the sheet when opened from the combat tracker not having the spellslot trackers since token id wasn't provided.
Fixes an issue where a token with a  custom stat block without initiative set couldn't be added to the combat tracker.
> Beta Fix - issue with custom stat blocks in the combat tracker

- Fog.js
Walls were being drawn on the temp canvas when their menu was closed if bucket fill was selected.
> Fix - issue where walls stayed visible when menu with bucket fill selected was closed

- Fog.js
If a wall was drawn after a window it would record the wall as the closest move stopping point. Opening/closing the window fixed this so I missed it. 
This should resolve it by only recording it when it's actually closer.
> Beta Fix - issue with windows allowing movement through them when a wall was drawn after.

- Token.js
Sometimes this offscreen canvas used for detecting moveable areas for players was undefined. Causing an error before tokens we're giving the draggable function.
> Fix - issue with tokens not being draggable when slower loads occur.

- Settings.js
Auto scaled maps were exporting incorrectly due to not reversing the auto scale.
> Fix - issue with export current scene on auto scaled maps

- CoreFunctions.js
- Startup.js
when using projector mode on different resolution windows it would scroll to same scroll coordinates not the center. This adjusts it to scroll to the center of view no matter the resolution.
> QoL - Projector mode will now scroll to center of view instead of edge

- TokenMenu.js
Fixes the players and open5e monster save modifiers in the quick roll menu. When player data got changed this didn't get updated and open5e was never added to it. 
Custom stat blocks are still to do on this.
> Fix - issue with player and open5e save modifiers in quick rolls

- ScenesPanel.js
Some maps take longer to load, it's already replacing the data we don't need to remove the container.
> Beta Fix - issue with grid wizard controls on video maps

- Main.js
- MessageBroker.js
Fix uvtt scenes map from overlay itself or other maps if we don't get the data back before another scene interaction occurs.
Example of bug:
> Fix - uvtt scene overlaying existing map if we don't get uvtt data back before another scene is loaded.

- ScenesPanel.js
Transparency is far too low - it doesn't need to be /4 on the intensity.
> Fix - UVTT light transparency on import.

- Fog.js
- ScenesHandler.js
- ScenesPanel.js
Fixes an issue where the grid overlay was stay stretched if hex stretching was done and swapped back to square. Manual adjustments are now reflected by the aligners when adjusting a square grid.
> Beta - issue with wizard scaling; Manual adjustments to square wizard should be reflected by the aligners.

- Startup.js
I've seen a few people stuck on ';start up complete' when joining as the DM. This is usually due to a map image request sending an error back. Getting them to manually remove the overlay then switch scenes fixes it so I'm forcing the overlay to be removed if it reaches that message.
> Fix - Ensure overlay is removed so DM doesn't get stuck on 'Start up complete'

- ScenesPanel.js
The skewing of hexgrids was a little too much per tick to get a good alignment when close. I think this brings it more inline with the square minor adjustments.
> Beta - Reduce the amount hexes get skewed per 'tick' of the slider to allow for more fine tune control

- ScenesHandler.js
- ScenesPanel.js
The offset was causing the grid to jump at certain values. This fixes that. Also updates the instructions for hex grids.
> Beta - Fix offset jumps when manually changing offsets in grid wizard; Adjust hex instructions to include skewing

- Journal.js
If quickly changing the folder structure somehow folders end up inside their parent each other causing an infinite loop looking for the parent folder. This prevents that - I'll look more into how it happens but this is a quick fix.
> Beta fix - prevent infinite loop on jounal folder parent.

- Fog.js
Token reveal during light should always be checked. We should debounce light checks more if necessary instead.
> Beta - issue with clunky token reveal

- Token.js
Walkable area had vpps and hpps reversed. On some maps rounding would be off a bit due to the point selected and the same square would be selected. This makes arrow key movement more reliable.
> Fix - issue with walkable area; A bit more reliable arrow key grid snapping.

- Fog.js
- Token.js
Some walls could be moved through with arrow keys since the los check was happening before the snap instead of after. Also some edge cases where it rounds so I check to more nearby points.
> Fix - prevent snapping through walls with arrow keys

- Journal.js
- TokenMenu.js
- abovevtt.css
Add an option to quick add a pc sheet that's not in the campaign as a custom stat block.
> Feat - Quick add PC npc links to a custom stat block so their sheet is opened. (Rolls still won't show up in game log unless they are in the campaign)

- MessageBroker.js
If the DM map is enabled on a UVTT map this gets run twice when it doesn't need to be.
> Fix - remove unnecessary uvtt request

- CharactersPage.js
- CoreFunctions.js
- Main.js
Example:
https://youtu.be/gG2SbYWOyWE
Prioritizes the DM view to roll in, when the vtt window is closed checks if another abovevtt window is still open, if not it should roll on the sheet normally again.
> Beta - pull non-campaign pc rolls into abovevtt and gamelog

- Main.js
- TokenMenu.js
This will be more useful in games were players have more than 1 pc but can be used to look at a non-private statblock as well. It won't have roll buttons - they load the same as they would outside abovevtt.
> Allow players to open other pc stat blocks. Mostly for people who play multiple pcs in 1 campaign or to view non-private stat blocks.

- CharactersPage.js
- Settings.js
This allows users to disable this capturing feature. While it allows rolls from pcs outside the campaign some people may have issues with it if they run tabs in the same window as the vtt. This gives them the option to disable it.
> Add setting to disable capturing of other pc tabs rolls.

- CharactersPage.js
The note rolls we're double rolling when ddb dice were disabled.
> Beta Fix - prevent double rolls for ddb disabled note rolls

- ScenesHandler.js
Currently undoing a token delete just places the token and doesn't update for players or on the server. This fixes that.
> Fix - Undoing a token delete should update the player view and sync to server

- TokensPanel.js
It looks like we're missing some monsters unless load more is used a bunch due to default sorting by book before alphabetical.
> QoL - Always sort open5e alphabetically instead of default by book.

- MessageBroker.js
When we load and I think occasionally other times we get undefined messages in the chat history that it tries to process. If undefined this just doesn't add it to the chat_pending_messages
> Fix - injected chat message error due to undefined.

- Token.js
I never added this settings to the list when they probably should have been.
> Fix - AoE tokens should be able to be locked, player restricted and reveal in fog

- SidebarPanel.js
- TokensPanel.js
This button doesn't behave as expected when searching.
> Fix - reveal hidden folders/tokens should remain active when searching

- SidebarPanel.js
- TokensPanel.js
When a custom image is set lets show it in the token panel. 
Also fixes an error on trying to delete a single token image if it's a open5e monster.
> QoL - Display first custom image in listing when set; Fix - Deleting custom images from open5e monsters with context menu;

- MessageBroker.js
- ScenesPanel.js
UVTT maps can take awhile to load and sometimes look like the extensions has crashed. This gives an indicator that it's still loading. 
Also add a loading indicator to uvtt grid wizard as it doesn't look like it's loading when first pressing the button. Clicking it again breaks the wizard - this prevents the 2nd click and lets the user know it's working.
> QoL - loading indicator for UVTT maps; Beta Fix - prevent double load of grid wizard on uvtt maps.

- Token.js
Some more snapping issues, should use float instead of int so that we don't get 0 when it's close to 1.
Add 5 to left and top when using arrow keys to make sure we're in the right square.
> Beta Fix - Some snapping issues where some small/medium tokens were being picked up as tiny; Fix sometimes moving to the wrong column with arrows keys

- Token.js
Since players share the same id lets keep it unless manually deleted.
> QoL - don't delete notes on player tokens when their token is deleted.

- CharactersPage.js
- Main.js
player id sometimes was getting ?abovevtt=true as part of it on refresh. This breaks at least the peer sharing of rulers/cursor.
> Fix - make sure playerid doesn't ever include url query string.

- ScenesPanel.js
Scenes don't have a `uuid` always set it looks like it's set in `id` now. This makes it so when a change happens and it's saved fog doesn't stay on the map.
> Fix - make sure scene settings include scene id

- Fog.js
- MessageBroker.js
Remove drawing light layer from the vision check. Add it's own function. Probably a good idea to rename these in the future
> Beta - More performance boosts for light; don't redraw to light overlay when checking light.

- Fog.js
Light bucket fill was extending past walls. This should resolve that.
> Fix - light bucket fill shouldn't extend past walls (stroke width should be 1)

- Main.js
- Startup.js
This should prevent the new `MAPS` from opening when we launch and when a sidebar item is clicked for players.
> Fix - issue with player view openning the map whenever the tabs are clicked.

- Fog.js
- Token.js
Brave browser randomizes pixels slightly to prevent fingerprinting in canvas. Since we are looking for black (0,0,0) pixels this breaks our checks to hide tokens and movement checks.
> Fix - Brave browser walls movement and hiding tokens.

- Fog.js
Text is causing errors on loading a scene preventing it from showing up and causing light not to draw either.
> Fix - Text causing errors on scene load.

- CharactersPage.js
Right click isn't captured due to not having a window.diceRoller - this resolves that.
> Fix - right click rolls when capturing from other tabs

- CharactersPage.js
- Main.js
- MessageBroker.js
- TokensPanel.js
Allows players to drop in extras as tokens if the DM is on the scene with them. Sends a message with the extra's customizations and baseid so the DM can grab it and place it. Should place in the center of players screen ~
> Feat - allow players to place extras as tokens.

- TokenMenu.js
Currently when hp/ac is disabled players don't get their own hp/ac in the token menu. This only allows it to show for their own token - still giving the option for people to hide other pcs for more gritty games where that isn't known.
> QoL - players should be able to see their own stats in the right click no matter the settings hiding hp/ac

- Main.js
- ScenesPanel.js
swaps google drive maps to their api link. This link only works when on dndbeyond like the uvtt links. So when opening in another tab I default to the original map link.
> Use google drive api link for maps. Hopefully this reduces the google drive cache/unable to load maps issue.

- Main.js
Also makes sure the related videos in help are only on the same channel.
> Fix - adjust youtube loop slightly to avoid related videos

- TokensPanel.js
Don't send ddb requests for custom stat blocks. Fixes 403 response.
> Fix - don't send fetch request for custom stat block monsters

- TokensPanel.js
Reported on discord - clicking while the filters page is loading causes it to close early saving our owned monsters filter as undefined. Breaking folders on load.
> Fix - Filters causing token folders to be uncollapseable if closed early.

- DiceRoller.js
- abovevtt.css
Allows d6 d8 etc in roll formulas. Automatically add 1's in front. 
Adds a message letting users know the roll was invalid and to hover for roll formats.
> QoL - chat rolls allow d6, d8 etc. Add invalid roll msg.

- Fog.js
Stop players tokens from disappearing on them in fog/darkness. Prevents losing their token and allows them to light a torch etc.
> QoL - players should always see their own player token even in fog/darkness.

- Fog.js
- Token.js
Removes some unnesecarry redrawing and placing of tokens. Just sets a class on them. Reduce run time on setting them as currently selected.
> QoL - performance improvement when selecting / deseleting tokens

- Main.js
- MessageBroker.js
- Token.js
- TokenMenu.js
- abovevtt.css
Examples
https://youtu.be/uzCM73HlXTg
> Token aura and light styles/animations

- CoreFunctions.js
- Main.js
Move all google images to the google drive api - as the images using it appear to be loading properly. Throttle may need to be adjusted to prevent rate limit issues.
> Fix - issue with google drive images failing to load.

- audio/ui.js
I just removed the button for now, hopefully they will make it possible to use this again for audio.
> Remove one drive button from audio tab - due to issues with one drive rolling everyone onto sharepoint servers.

- Settings.js
- Token.js
Add "Bloodied" option for token health aura style.
Draws the red ring only if HP < 50%
Could enable other percentages pretty easily by adding to options menu
> Bloodied Health Aura Style

- Fog.js
This was clearly an incorrect placement of `)`
> fix: fix alpha argument being ignored in WaypointManagerClass.draw()

- MessageBroker.js
I noticed feature request in discord, and wanted to do it. Turns out @Azmoria beat me to it by 12 hours or something.
I noticed that it sorta may crash if pc happens to not have any languages profficiency (`knownLanguages.includes`), and while there I've decided to cleanup tabulation a bit, hope that's okay.
> refactor: small cleanup for pc-does-not-understand-language feature

- CoreFunctions.js
- Journal.js
- Main.js
- MessageBroker.js
With last `.toLowerCase()` change I've noticed that this is done 3 times in 3 different places, which triggers my internal "time to extract it" breakpoint, so I did that.
I did not add `toLowerCase()` for comparison in MessageBroker.js, though it could be added there
> refactor: extract get_my_known_languages()

- Main.js
- abovevtt.css
I've reinstalled os and was reminded that splashscreen is transparent on initially before image is fetched for the first time becuase there is no background color.
Maybe this could be classified as a fix tho
> refactor: provide bg color for splash screen so it's never transparent

- DDBApi.js
- Load.js
- LoadCharacterPage.js
I've been getting flagged as 'we think your using automated tools to browse' when refreshing while working on abovevtt recently. This seems to resolve the issue - I think it's due to DDB making their own api requests on load and us making them too quickly afterwards.
> Fix - add 1 second delay before loading scripts to avoid being flagged as bot when refreshing.

- Load.js
- LoadCharacterPage.js
I was wrong in my assumption just looks like it was coincidence. It's happening in a incognito window, no extensions loaded, on the campaign page at minimum.
> Internal - remove timeout as it doesn't appear to be the cause, just happened in incognito window no extensions

- Startup.js
Not all campaigns use and require youtube to operate. If youtube is blocked in your country, this will fail to load, killing the startup.
To avoid that, we just console error the failure instead.
This should probably resolve all those failed to load youtube duplicates.
Refs: #2637 (and others)
> fix: don't throw if loading youtube script fails

- DDBApi.js
So it was never this request it was having dev tools open that was flagging. Changing this back to match DDB's request on the encounter builder page.
> Internal - match DDB request for config data

- audio/mixer.js
- audio/track.js
- audio/ui.js
Added a "Shuffle Play" to the continuous button. When depressed, after a track has finished, the next track is randomly selected from the current playlist. 
Added two new buttons. 
- Add Tracks to Mixer
- Adds tracks from the current view to the mixer. Warns if more than 50 are requested. 
- Add Shuffled
- Same as above, only the list is shuffled first. 
Random is seeded using the timestamp to prevent repeatable random outcomes. 
- Existing behavior works as before (OR filtering). 
- Added quoted strings, that require an exact match and work for name and tags. 
- For example, 
- `A Clash of Fang and Flame` matches 448 tracks
- `"A Clash of Fang and Flame"` matches 1 track name
- `Modern-Warfare` matches 53 tracks (from the tag)
- `"Modern-Warfare"` matches 29 tracks (from the exact tag)
> Audio Quality of Life updates

- MessageBroker.js
If a map used a DD2VTT (or a UVTT) file as its base, and an image file is added as a DM map, the DM map would not appear for the DM (IE  the DM would see the player map)
> Fix - DM map is used on DD2VTT map files if available

- Fog.js
- Main.js
Added new drawing layer;
Added location options in the draw dropdown;
Add drawing to layer based on location option selected;
The code on line 1481 should make it so that any pre-existing drawings will default to 'above fog', the way they currently are, so this shouldn't break people's current drawings.
The only things I'm a bit iffy on for these changes are
1. The location I put the new _drawOverlayUnderFogDarkness_ draw layer in the HTML - I'm happy for this to be moved somewhere that makes more sense, this was just a spot that worked.
2. The labelling in the dropdown - I wanted to make sure that the labels were short enough to not needlessly widen that dropdown, but they may not be descriptive enough? Open to change.
3. Clearing the draw layer - currently, if you click 'clear draw' in …
> QoL - Option for drawings below darkness/fog

- ChatObserver.js
- MessageBroker.js
If the DM has one or more tokens selected, speak as those tokens;
Added title attribute to the character name span in the chat bar so that long titles (such as long character names or, more relevant to this PR, multiple character names can all be seen on hover.
#1849 
In ChatObserver, the sendChatMessage function checks whether the current user is the DM and if they have any tokens selected. 
- If the current user is a player, the message sends as that players character.
- If the current user is the DM with no tokens selected, the message sends from 'THE DM'.
- If the current user is the DM with one or more tokens selected (PC or NPC), the message sends as if from those characters.
Considerations
1. Should the DM be able to send chat messages as if from another player character? Currently …
> If the DM has one or more tokens selected, speak as those tokens;

- Journal.js
- MessageBroker.js
- abovevtt.css
#2411 
Using the existing window.MB.sendMessage functionality and sending _popup: false_ instead of true. When popup == false, find the note popup with data-id == note.id and remove it from the HTML. 
Tested with 
1. Notes that were originally forced open by the DM - forces them closed.
2. Notes that were originally shared to the player and opened by them - forces them closed.
3. Multiple notes open - only forces the one note closed.
> Added DM-only button to force close a note for all players

- Journal.js
#2936 
The idea here was to do the following:
1. Get a list of notes that contain the searchText, save that to array 'relevantNotes'.
2. Get a list of folders that contain the searchText, save that to array 'relevantChapters'.
3. Traverse the structure up to the root to get all parent folders, add those to array 'relevantChapters'.
4. Traverse the structure down as far as possible for all **folders that were directly searched (see Mirkwood example below)** and add those folders and their notes to the relevant arrays.
5. When rendering a folder/note, it first checks if that folder/note is in the relevantNotes/relevantChapters array. If it is, it renders - if it is not, it doesn't.
This was slightly more complex than initially anticipated due to the way the Journal was initially set up …
> Enhancement - journal search

- KeypressHandler.js
Most Mac users have Cmd-Space bound to Spotlight globally, so I think it's preferable to have Control-space be the binding for find token (on both mac and windows)
> Most Mac users would prefer control here

- .github/workflows/safari-release-build.yml
- safari/build.sh
I missed a workflow option to get the right build extension into environment.js for safari (no changes except safari build)
> correct build extension in environment.js for safari build

- Settings.js
- Token.js
- TokenCustomization.js
- TokenMenu.js
- TokensPanel.js
- abovevtt.css
This is a start to allowing different images to be styled/positioned differently for the same token. I often adding multiple images to players/monsters that they often aren't able to use the same style/position and look their best. 
There's still quite a bit to do with this.
Currently I just have it reopening the sidebar when a token is selected - instead it should just set the values of the inputs, toggles etc. This was mostly just for testing purposes instead of building to refresh stats section. 
Resetting defaults while customizing a specific image should remove its customizations. 
Deleting the image should remove it's info from data.
https://github.com/user-attachments/assets/0724fde7-b0b4-4fbd-aa9a-e16a9e2eb88f
> QoL - allow individual defaults to be set per image for tokens

- Journal.js
- ScenesPanel.js
- Settings.js
- SidebarPanel.js
The idea here is to create a note that applies to a given scene.
It does this by 
1. When the 'Open Scene Note' option is selected, create a hidden note within the journals and open it for editing.
2. User can edit the note as normal.
3. When the user closes the note, the note data is saved to the scene and the hidden note is deleted.
4. When the user selects the 'Open Scene Note' option again, the saved note data is used to re-generate the hidden note and open it for editing.
I did it this way to reuse as much of the existing note infrastructure as possible. Also, since the note data is saved to the scene it should be exported with the rest of the scene data if needed.
Possible next step - if a scene has note data, add an icon on the scene that opens the note without having to use the …
> Create scene notes
